### ISSUE TITLE
Issue with AppInsights in Java Web App

### ISSUE THREAD

**Issue by shwetamumbarkar** [microsoft/ApplicationInsights-Java#1013]
We find an intermittent issue of AppInsights log not being sent to Azure in our Java Web App. 

We tried the SDK logger and get the below trace:

```
TRACE 09-08-2019 10:42:02.290+0000, 576(HeartBeatProvider_propertyUpdateService-0): added heartbeat property osVersion - Windows Server 2016
TRACE 09-08-2019 10:42:02.290+0000, 576(HeartBeatProvider_propertyUpdateService-0): added heartbeat property sdkVersion - java:2.4.0
TRACE 09-08-2019 10:42:02.290+0000, 524(default task-11): Registering PC 'DeadLockDetector'
TRACE 09-08-2019 10:42:02.305+0000, 576(HeartBeatProvider_propertyUpdateService-0): added heartbeat property processSessionId - f52c879c-7341-4712-869c-43841ce87ea5
TRACE 09-08-2019 10:42:02.305+0000, 524(default task-11): Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
TRACE 09-08-2019 10:42:02.305+0000, 576(HeartBeatProvider_propertyUpdateService-0): added heartbeat property jreVersion - 1.8.0_151
TRACE 09-08-2019 10:42:02.321+0000, 524(default task-11): Registering performance counter: Processor\% Processor Time [_Total]
TRACE 09-08-2019 10:42:02.336+0000, 524(default task-11): Registering performance counter: Memory\Available Bytes []
TRACE 09-08-2019 10:42:02.336+0000, 524(default task-11): Registering performance counter: Process\IO Data Bytes/sec [java]
TRACE 09-08-2019 10:42:02.336+0000, 524(default task-11): Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
TRACE 09-08-2019 10:42:02.352+0000, 524(default task-11): Registering PC 'JSDK_ProcessCpuPerformanceCounter'
TRACE 09-08-2019 10:42:02.352+0000, 524(default task-11): Registering PC 'JSDK_WindowsPerformanceCounterAsPC'
TRACE 09-08-2019 10:42:02.399+0000, 524(default task-11): TraceTelemetryFilter: set severity level to Information
ERROR 09-08-2019 10:42:07.430+0000, 585(ActiveTransmissionNetworkOutput_1-0): Failed to send.
Stack Trace:
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No X509TrustManager implementation available
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.microsoft.applicationinsights.core.dependencies.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at com.microsoft.applicationinsights.core.dependencies.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:81)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:185)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No X509TrustManager implementation available
	at sun.security.ssl.DummyX509TrustManager.checkServerTrusted(SSLContextImpl.java:1184)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 26 more

TRACE 09-08-2019 10:42:07.430+0000, 585(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.ErrorHandler
TRACE 09-08-2019 10:42:07.446+0000, 585(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.PartialSuccessHandler
TRACE 09-08-2019 10:42:07.446+0000, 585(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.ThrottlingHandler.
ERROR 09-08-2019 10:43:00.360+0000, 640(ActiveTransmissionNetworkOutput_1-1): Failed to send.
Stack Trace:
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No X509TrustManager implementation available
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.microsoft.applicationinsights.core.dependencies.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at com.microsoft.applicationinsights.core.dependencies.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:81)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:185)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No X509TrustManager implementation available
	at sun.security.ssl.DummyX509TrustManager.checkServerTrusted(SSLContextImpl.java:1184)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 26 more
```
Any clue how this can be fixed?

We've tried the below link, but didn't help.

https://github.com/microsoft/ApplicationInsights-node.js/issues/180

**Comment by shwetamumbarkar** [comment]
We are using same container for two different WARS which are running inside JBOSS application server. Both WARS are currently refer to two different set of truststore and keystore. 
We have added truststore and keystore file path in jboss configuration folder and also added path in standalone.xml file of JBOSS. 
We have analysed and identify application insight is not able to find the path for truststore and hence throwing error as javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No X509TrustManager implementation available.

**Solution**:
We have added truststore and keystore path in jboss startup and now application insight able to send telemetry data.

Please let us know if you have came across similar kind of issue in past. Also it will be helpful if you have any suggestion on the approach we have used to resolve the issue.

Awaiting for response.

**Comment by littleaj** [comment]
I worked on a similar issue in tomcat. The issue turned out to be that the trustStore was of type JKS, but the property `javax.net.ssl.trustStoreType` was set to `pkcs12`.

Another way this can happen is if the value of `javax.net.ssl.trustStore` points to a cert and not a keystore. If this is the case, you can use [`keytool`](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html) to create a keystore.

I also found a few articles saying this can occur if the trustStore file is corrupted. You can verify that (and its type) using the instructions in the next paragraph. If you are not able to list the contents, then the file could be corrupted and should be recreated.

If you run `keytool -list -keystore <your trust store>`, somewhere in the first 5 lines shows the keystore type. This should be the value of `javax.net.ssl.trustStoreType`. The default value is JKS.

Let me know if any of those suggestions worked for you.
