### ISSUE TITLE
Local hosted Java app fails to send telemetry, while telemetry from .NET app works on same machine

### ISSUE THREAD

**Issue by vdcloud** [microsoft/ApplicationInsights-Java#1087]
I have a maven java 8 app where i have configured Application Insights. I have the SDKLogger set to console and can see the AI: TRACE logs in the console output. However, the java app is unable to send the telemetry to Application insights instance on Azure. 

The Java app fails with the following error. However, **on the same machine, I tried a ASP.NET Core App with same instrumentation key and it works like a charm.** I am behind a corporate proxy and firewall. However, that did not stop the .NET Core app from sending telemetry.

```
**AI: ERROR 07-10-2019 20:04:59.600+0000, 167(ActiveTransmissionNetworkOutput_1-5): Failed to send, socket exception.**
Stack Trace:
com.microsoft.applicationinsights.core.dependencies.http.conn.HttpHostConnectException: Connect to dc.services.visualstudio.com:443 [dc.services.visualstudio.com/52.162.110.67] failed: Connection timed out: connect
        at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:82)
        at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:186)
        at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.microsoft.applicationinsights.core.dependencies.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 16 more
```

**Comment by littleaj** [comment]
@vdcloud, Make sure your java proxy settings are correct: https://github.com/microsoft/ApplicationInsights-Java/wiki/Using-an-HTTP-Proxy

Let us know if that doesn't work.

**Comment by vdcloud** [comment]
With -Dhttps.proxyHost and -Dhttps.proxyPort settings, the runtime socket exception goes away (i.e. no AI: ERROR in console output, only AI: TRACE statements). However, the https requests to my Java API or any other telemetry still does not show up in the App Insights Performance, Availability or any other tiles. I waited/refreshed multiple times to allow for flush interval to elapse.

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you
