### ISSUE TITLE
FromSeverityLevel settings

### ISSUE THREAD

**Issue by 123Jun321** [microsoft/ApplicationInsights-Java#1269]
**Is your feature request related to a problem? Please describe.**
we just want to know can we modify the trace level(FromSeverityLevel ) without restarting the app?
if can, could you tell us how to do that?

Thanks first！

**Describe the solution you would like**
Describe what you want to happen.

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by MS-jgol** [comment]
@123Jun321 What version of Application Insights Java are you using? 

I strongly recommend to use the Java 3.0 agent, which does not require restarting the app: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

Here are the available configuration options:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config

**Comment by 123Jun321** [comment]
Hi @MS-jgol ，Thanks very much first.
we used applicationinsights-web-auto 2.5.0

And actually we want to control the level of trace logs which were sent the Application Insights, can we use the below JSON to do this?

{
  "instrumentationSettings": {
    "preview": {
      "instrumentation": {
        "logging": {
          "threshold": "ERROR"
        }
      }
    }
  }
}

**Comment by MS-jgol** [comment]
@123Jun321 
You can control the trace logs in Java 3.0 agent, here are the instructions:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#application-log-capture

**Comment by 123Jun321** [comment]
Hi  @@MS-jgol  

We have a test in our local with tomcat 8.5, but when we changed the ApplicationInsights.json, we didn't found it worked.

there were steps how we test:
1.deploy the web app to tomcat
2.config the tomcat as the article said https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-arguments#tomcat-8-windows  
3.run it, visit the web app
4.change the ApplicationInsights.json, we changed the role name and log level
5.visit the web app again, but it didn't work.

os:win 10
tomcat version: 8.5.31.0
[tomcatlog.txt](https://github.com/microsoft/ApplicationInsights-Java/files/4890678/tomcatlog.txt)

**Comment by 123Jun321** [comment]
By the way, the region of Application Insights we used  is in china

**Comment by MS-jgol** [comment]
@123Jun321 Just to confirm: am I understanding this correctly that after step 2, when you run the app, the telemetry is working, and after you change the config settings it stops working? Meaning, the config changes are not having any effect, correct?

If the above is true, can you please send us your config file after the changes were made (make sure to remove all private information...)?

On a side note, the region does not matter, as Java 3.0 is supported in all regions.

**Comment by 123Jun321** [comment]
@MS-jgol  I will offer more details about my steps.
firstly, the json was like:
`{
    "instrumentationSettings": {
        "connectionString": "InstrumentationKey=2a7a983b-c398-c4c3-8d0e-f19b92a03d70;EndpointSuffix=applicationinsights.azure.cn",
        "preview": {
            "instrumentation": {
                "logging": {
                    "threshold": "ERROR"
                }
            },
            "roleName": "my cloud role123"
        }
    }
}`

and it worked, when we observed the Application insights, we can see that the role name was "my cloud role123" and the log only contained error level. 
Then we change the JSON without restarting web app, like this:
`{
    "instrumentationSettings": {
        "connectionString": "InstrumentationKey=2a7a983b-c398-c4c3-8d0e-f19b92a03d70;EndpointSuffix=applicationinsights.azure.cn",
        "preview": {
            "instrumentation": {
                "logging": {
                    "threshold": "INFO"
                }
            },
            "roleName": "my cloud role"
        }
    }
}`
 and visit the web app again, but the role name and the log were the same before whitout any changes .

**Comment by MS-jgol** [comment]
@123Jun321 Thank you for explaining the case in more details! 
Would you mind restarting the app with the new configurations in place?

**Comment by 123Jun321** [comment]
@MS-jgol  when I restarted, it worked OK and telemetry logs were sent to AI according to the configuration JSON.
And we found there was an error in tomcat log:
Are they related?

ERROR i.o.auto.tooling.HelperInjector - Error preparing helpers while processing class org.springframework.core.io.ClassPathResource for ClassPathResourceInstrumentation. Failed to inject helper classes into instance ParallelWebappClassLoader
  context: springmvctest
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@27ead29e

java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:607)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
        at io.opentelemetry.auto.tooling.HelperInjector.injectClassLoader(HelperInjector.java:184)
        at io.opentelemetry.auto.tooling.HelperInjector.transform(HelperInjector.java:134)
        at net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2612)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10117)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10833)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10780)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2338)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:828)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1277)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1136)
        at org.springframework.web.servlet.DispatcherServlet.<clinit>(DispatcherServlet.java:278)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1044)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:773)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/micrometer/core/instrument/step/StepMeterRegistry
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:603)
        ... 46 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.micrometer.core.instrument.step.StepMeterRegistry
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1308)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1136)
        ... 52 common frames omitted

**Comment by trask** [comment]
Hi @123Jun321, this error message should be harmless, but also it should be fixed now in 3.0.0-PREVIEW.5: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.5

**Comment by 123Jun321** [comment]
hi @trask  should we have a test in preview 5 ?

**Comment by trask** [comment]
Yes, please try it out 👍

**Comment by 123Jun321** [comment]
Hi, the issue still existed when we use 3.0.0-PREVIEW.5
