### ISSUE TITLE
Dependency is not being tracked in Application Insights

### ISSUE THREAD

**Issue by ImeshaC** [microsoft/ApplicationInsights-Java#1298]
We have been working on getting dependency tracking working on Application insights using the following documentation:

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-agent

Current versions we are using are:
Application Insights Agent and applicationinsights-web-auto in the POM.xml file - 2.6.1
MySQL connector - 5.1.31

Please see the attached image with the path to the AI-Agents.xml, ApplicationInsights.xml and applicationinsights-agent-2.6.1.jar - 
![File Structure](https://user-images.githubusercontent.com/63796616/90416683-b3926780-e0aa-11ea-82e3-18bed5e31b91.png)

All the attempts below have been made on both a Window and a Linux App Service.

Locally when we add all these files into the resources folder and run the application with the paths to these files configured, dependencies are tracked without a problem. However, replicating the same configuration on the App Service displays this exception:

_2020-08-17T12:03:27.903658570Z: [ERROR]  17-Aug-2020 12:03:27.891 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
2020-08-17T12:03:27.903673570Z: [ERROR]         org.apache.catalina.LifecycleException: Failed to start component [/AI-Agent]
2020-08-17T12:03:27.903688470Z: [ERROR]                 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
2020-08-17T12:03:27.903693670Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
2020-08-17T12:03:27.903697370Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
2020-08-17T12:03:27.903701470Z: [ERROR]                 at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
2020-08-17T12:03:27.903712370Z: [ERROR]                 at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
2020-08-17T12:03:27.903716170Z: [ERROR]                 at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1833)
2020-08-17T12:03:27.903719770Z: [ERROR]                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-08-17T12:03:27.903723270Z: [ERROR]                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-17T12:03:27.903726770Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-08-17T12:03:27.903730270Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-08-17T12:03:27.903733770Z: [ERROR]                 at java.lang.Thread.run(Thread.java:748)
2020-08-17T12:03:27.903737470Z: [ERROR]         Caused by: org.apache.catalina.LifecycleException: Failed to process either the global, per-host or context-specific context.xml file therefore the
[/AI-Agent] Context cannot be started.
2020-08-17T12:03:27.903741070Z: [ERROR]                 at org.apache.catalina.startup.FailedContext.startInternal(FailedContext.java:199)
2020-08-17T12:03:27.903744570Z: [ERROR]                 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
2020-08-17T12:03:27.903748170Z: [ERROR]                 ... 10 more
2020-08-17T12:03:27.903751570Z: [ERROR]  17-Aug-2020 12:03:27.900 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying configuration descriptor [/
home/site/wwwroot/AI-Agent.xml]
2020-08-17T12:03:27.903755270Z: [ERROR]         java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [/AI-Agent]
2020-08-17T12:03:27.903758870Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:758)
2020-08-17T12:03:27.903762370Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
2020-08-17T12:03:27.903765870Z: [ERROR]                 at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
2020-08-17T12:03:27.903770170Z: [ERROR]                 at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
2020-08-17T12:03:27.903773670Z: [ERROR]                 at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1833)
2020-08-17T12:03:27.903777270Z: [ERROR]                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-08-17T12:03:27.903780670Z: [ERROR]                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-17T12:03:27.903784170Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-08-17T12:03:27.903787670Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-08-17T12:03:27.903791070Z: [ERROR]                 at java.lang.Thread.run(Thread.java:748)_

We attempted the Java agents path as a start up command as well as a JAVA_OPTS but still getting the same exception.

From the logs above, as it was looking at AI-Agents in /home/site/wwwroot, the ApplicationInsights.xml as well as the Java Agent files were moved to this folder which also displayed the same exception but for the ApplicationInsights.xml file:

_2020-08-18T11:18:54.583510165Z: [ERROR]         org.apache.catalina.LifecycleException: Failed to start component [/ApplicationInsights]
2020-08-18T11:18:54.583515565Z: [ERROR]                 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
2020-08-18T11:18:54.583519665Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
2020-08-18T11:18:54.583523465Z: [ERROR]                 at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
2020-08-18T11:18:54.583555865Z: [ERROR]                 at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
2020-08-18T11:18:54.583569265Z: [ERROR]                 at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
2020-08-18T11:18:54.583573565Z: [ERROR]                 at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1833)
2020-08-18T11:18:54.583577365Z: [ERROR]                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-08-18T11:18:54.583581365Z: [ERROR]                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-18T11:18:54.583585065Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-08-18T11:18:54.583588965Z: [ERROR]                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-08-18T11:18:54.583592665Z: [ERROR]                 at java.lang.Thread.run(Thread.java:748)_

Please can you advice on whether any configurations are missing or if further configurations are required.

**Comment by MS-jgol** [comment]
@ImeshaC 
Can you please try the Application Insights Java 3.0 instead? It is super easy to deploy and I believe it will solve your problem:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by ImeshaC** [comment]
@MS-jgol 
Thank you for your response.  I tried with Application Insights Java 3.0 and dependency did start tracking however, we couldn't see a correlation between the requests and the dependencies. 

Initially we were seeing multiple requests going out and no dependencies but now we can't see the individual requests.

Here is a snippet of the graphs we were seeing after changing it to the 

Requests:
![image](https://user-images.githubusercontent.com/63796616/91173311-8743a000-e6d5-11ea-8c1f-1d21244538f5.png)

Dependencies:
![image](https://user-images.githubusercontent.com/63796616/91173445-c245d380-e6d5-11ea-8bc8-512ec7b0d159.png)

Detailed view of the dependency, as you can see here it hasn't correlated to a request:

![image](https://user-images.githubusercontent.com/63796616/91175115-2c5f7800-e6d8-11ea-949f-b3e62bf0ec36.png)

![image](https://user-images.githubusercontent.com/63796616/91175679-13a39200-e6d9-11ea-8dbe-d331389593db.png)

**Comment by MS-jgol** [comment]
@ImeshaC Would you be able to open a support ticket in Azure Portal?
KQL (Kusto Query Language) to look up and query the logs to see if the dependencies/requests show up there?
