### ISSUE TITLE
Unwanted exception: "InstrumentationKey must be null or empty"

### ISSUE THREAD

**Issue by lzu4** [microsoft/ApplicationInsights-Java#1333]
### Expected behavior
No error should be thrown, since there was no instrumentation key provided.

### Actual behavior
Error is thrown when the Instrumentation key is empty.

### To Reproduce
Use the applicationinsights-agent-2.6.2 and applicationinsights-web-auto.

#### Sample Application
applicationinsights-web-auto

### System information
Please provide the following information:
 - SDK Version: 
applicationinsights-agent-2.6.2, applicationinsights-web-auto
 - OS type and version: Windows 10
 - Application Server type and version (if applicable): Wildfly
 - Using spring-boot? No.
 - Additional relevant libraries (with version, if applicable): ---

### Logs
unable to perform correlation :java.lang.IllegalArgumentException: instrumentationKey must not be null or empty
	at com.microsoft.applicationinsights.web.internal.correlation.InstrumentationKeyResolver.resolveInstrumentationKey(InstrumentationKeyResolver.java:73)
	at com.microsoft.applicationinsights.web.internal.correlation.TraceContextCorrelation.getAppId(TraceContextCorrelation.java:277)
	at com.microsoft.applicationinsights.web.internal.correlation.TraceContextCorrelation.resolveCorrelation(TraceContextCorrelation.java:89)
	at com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.resolveCorrelation(WebRequestTrackingTelemetryModule.java:133)
	at com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.onBeginRequest(WebRequestTrackingTelemetryModule.java:114)
	at com.microsoft.applicationinsights.web.internal.WebModulesContainer.invokeOnBeginRequest(WebModulesContainer.java:59)
	at com.microsoft.applicationinsights.web.internal.httputils.HttpServerHandler.handleStart(HttpServerHandler.java:97)
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:131)

**Comment by heyams** [comment]
@lzu4 thank you for reporting.  I will try to do a repro and get back to you soon.

**Comment by heyams** [comment]
This is expected for Java legacy SDK.  It just logged the exception and didn't crash the app. You can disable logging entirely if that bothers you or upgrade to our [latest 3.0 agent](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7). We add this as a way for customers to disable Application Insights monitoring.

**Comment by lzu4** [comment]
Regardless whether expected or not, it is illogical. I do not provide any key, but the exception says: "InstrumentationKey must be null or empty"..

**Comment by heyams** [comment]
We will release 3.0 agent GA in early November 2020, and we don't have any plans to release anything new include bug fixes on the 2.x agent. Hope that helps.

**Comment by trask** [comment]
> **It does crash the request** for which it is trying to create metrics for in some cases

Hi @lzu4, can you provide a repro where this behavior is crashing the request? This would be a bug, and we would fix this if that's the case. Otherwise, we recommend updating to 3.0 which will be GA soon.

**Comment by lzu4** [comment]
We will test the 3.0 early November and see how it goes. Thanks.

**Comment by heyams** [comment]
I'm going to close this issue for now.  Thanks @lzu4.

**Comment by lzu4** [comment]
I've just checked the agent 3.0 and it does not crash the requests like the 2.x did but **unwanted error log** is still there when no key provided: "No connection string or instrumentation key provided"

Log:
Caused by: com.microsoft.applicationinsights.agent.bootstrap.configuration.ConfigurationBuilder$ConfigurationException: No connection string or instrumentation key provided
        at com.microsoft.applicationinsights.agent.internal.BeforeAgentInstaller.start(BeforeAgentInstaller.java:111)
        at com.microsoft.applicationinsights.agent.internal.BeforeAgentInstaller.beforeInstallBytebuddyAgent(BeforeAgentInstaller.java:84)
        at io.opentelemetry.javaagent.tooling.BeforeAgentInstaller.beforeInstallBytebuddyAgent(BeforeAgentInstaller.java:9)

**Comment by heyams** [comment]
I was able to repro. Will fix it. Thanks. I have created a work item to track this.

**Comment by trask** [comment]
hi @lzu4, we have cleaned up the message, it should read something like this now (without the big stack trace):

```
2021-01-04 15:24:03.446-08 ERROR c.m.applicationinsights.agent -
*************************
ApplicationInsights Java Agent 3.0.1-BETA.2 failed to start
*************************
Description:
No connection string or instrumentation key provided

Action:
Please provide connection string or instrumentation key.
```

we don't want to suppress the message completely, because this is a common error for the instrumentation key to be accidentally empty
