### ISSUE TITLE
Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat'

### ISSUE THREAD

**Issue by rob-oberbeck** [microsoft/ApplicationInsights-Java#1338]
### Expected behavior
Run spring application without errors.
How to disable Performance Counters for App Insights Java Agent 3.0.0?

### Actual behavior
App Insights Agent is not able to read the Performance Counters from file `/proc/stat` and `/proc/{id}/io`.

### To Reproduce

Run the Azure Monitor Application Insights agent as described in [Java codeless application monitoring Azure Monitor Application Insights - public preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent).

#### Sample Application
Use [Spring Initializr](https://start.spring.io/) to create web application and set Azure App Insights Agent when running the application (`-javaagent:applicationinsights-agent-3.0.0-PREVIEW.7.jar`).

### System information
Please provide the following information:
 - SDK Version: applicationinsights-agent-3.0.0-PREVIEW.7.jar
 - OS type and version: macOS Catalina
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes.
 - Additional relevant libraries (with version, if applicable): none

### Logs
```
2020-10-01 11:59:00.789+02 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/17177/io': Can not read
2020-10-01 11:59:00.790+02 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read

2020-10-01 11:59:13.290  INFO 17177 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1599 ms

2020-10-01 12:00:00.795+02 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/17177/io': Error while parsing file: 'JSDK_ProcessIOPerformanceCounter'
java.io.FileNotFoundException: /proc/17177/io (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.getCurrentIOForCurrentProcess(UnixProcessIOPerformanceCounter.java:102)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.report(UnixProcessIOPerformanceCounter.java:66)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-10-01 12:00:00.797+02 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Error while parsing file: 
java.io.FileNotFoundException: /proc/stat (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.getLineOfData(UnixTotalCpuPerformanceCounter.java:102)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.report(UnixTotalCpuPerformanceCounter.java:62)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by trask** [comment]
Hi @rob-oberbeck, thanks for reporting this! I have seen another MacOS user report this, I suspect we need to capture performance counters differently on MacOS.

**Comment by rob-oberbeck** [comment]
Hi @trask,
I deployed the application including the app insights Java agent version 3 onto our Azure Kubernetes cluster and I still get this error message.
The Docker image is based on Ubuntu 16.04.
Luckily, I can see the request counts and logs on the insights website.
I most importantly need Azure Log Analytics to be working, is there a configuration to simply disable the performance counters?

Not really related to this issue but I tried to get insights running by following [Configure a Spring Boot Initializer app to use Application Insights](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-java-applicationinsights).
Even though I followed all the steps I could not see any metrics or logs, but I did not get an error message this time.

Thank you.

**Comment by pauldaustin** [comment]
Any status on this?

One option could be when you get the not found error for the first time you log a warning that that stat is not going to be reported. Then don't execute that call again in that run of the application

**Comment by mab** [comment]
I run into the same issue with agent 3.0.2 running a Spring Boot application with latest 2.4.2 and fabric8/java-centos-openjdk8-jdk:1.8.1 as base image. Adding only a simple micrometer timer raises the exception mentioned above and blocks the service. 

```
    @GetMapping
    @Timed
    public String foo() {
      return "bar";
    }
```

**Comment by raeperd** [comment]
I have same issue on m1 MacOS Big sur 11.2.3.
Hopefully application logs are sent to application-insights as i intended. 

```
$ sudo java -jar -Dspring.profiles.active=release -javaagent:./build/libs/applicationinsights-agent-3.0.2.jar ./build/libs/my-application-jar.jar
Password:
2021-03-15 17:33:00.906+09 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/22607/io': Can not read
2021-03-15 17:33:00.907+09 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read
2021-03-15 17:33:04.692+09 INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.0.2 started successfully
```

**Comment by OllisGit** [comment]
Issue appears every minute on my mac.
```Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/44777/io': Error while parsing file: '\Process(??APP_WIN32_PROC??)\IO Data Bytes/sec'```

Fullstacktrace
```
2021-03-16 22:33:32.543+01 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Error while parsing file: 
java.io.FileNotFoundException: /proc/stat (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.getLineOfData(UnixTotalCpuPerformanceCounter.java:98)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.report(UnixTotalCpuPerformanceCounter.java:63)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:232)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:835)
2021-03-16 22:34:32.550+01 ERROR c.m.a.i.p.AbstractUnixPerformanceCounter - Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/44777/io': Error while parsing file: '\Process(??APP_WIN32_PROC??)\IO Data Bytes/sec'
java.io.FileNotFoundException: /proc/44777/io (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.getCurrentIOForCurrentProcess(UnixProcessIOPerformanceCounter.java:98)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.report(UnixProcessIOPerformanceCounter.java:67)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:232)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

**Comment by trask** [comment]
we just changed the way that the 3.0 agent captures these native O/S performance counters, if you have a chance, please try the latest SNAPSHOT build: [applicationinsights-agent-3.0.3-BETA.2-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6180425/applicationinsights-agent-3.0.3-BETA.2-SNAPSHOT.jar.zip)

**Comment by trask** [comment]
Hi all, I'm hoping this issue is resolved now in [3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2)

**Comment by OllisGit** [comment]
Hi @trask,

I can confirm that my local application works now without the issue. Thx, a lot!!!

Now the question is:  When will this version be available at maven-central repository ;-)

**Comment by trask** [comment]
Took a few hours to get there, but I see it now: https://search.maven.org/search?q=g:com.microsoft.azure%20a:applicationinsights-agent

**Comment by malmyros** [comment]
I am getting the same issue on my mac, so I am looking forward to the 3.0.3 release. 

We have just started trying this dependency, so hopefully once this is resolved we can put it to production.

**Comment by trask** [comment]
3.0.3 is released: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3
