### ISSUE TITLE
Environment variables are preffered to project specific configuration

### ISSUE THREAD

**Issue by WoodenAndrew** [microsoft/ApplicationInsights-Java#1533]
### Expected behavior
Connection string value is read from applicationinsights.json file when APPLICATIONINSIGHTS_CONNECTION_STRING environment variable is set

### Actual behavior
Connection string value is read from APPLICATIONINSIGHTS_CONNECTION_STRING instead of the value in applicationinsights.json file

### To Reproduce
Set environment variable APPLICATIONINSIGHTS_CONNECTION_STRING to any valid connection string (malformed strings suffice. ex. those with just instrumentation key)
Create applicationinsights.json file with different connection string
Run java application with applicationsinsights-agent-3.0.2.jar

#### Sample Application
```ps1
$env:APPLICATIONINSIGHTS_CONNECTION_STRING="asdf"
java -javaagent:applicationinsights-agent-3.0.2.jar -jar main.jar
```

### System information
Please provide the following information:
 - SDK Version: -
 - OS type and version: windows server 2012
 - Application Server type and version (if applicable): -
 - Using spring-boot? No.
 - Additional relevant libraries (with version, if applicable): -
 - Agent version: 3.0.2

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

```
2021-03-03 09:37:50.374+02 ERROR c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.0.2 failed to start
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:175)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:80)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
        at com.microsoft.applicationinsights.agent.bootstrap.MainEntryPoint.start(MainEntryPoint.java:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:87)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:96)
        ... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid connection string
        at com.microsoft.applicationinsights.TelemetryConfiguration.setConnectionString(TelemetryConfiguration.java:230)
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.setConnectionString(TelemetryConfig
urationFactory.java:154)
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFa
ctory.java:89)
        at com.microsoft.applicationinsights.agent.internal.BeforeAgentInstaller.start(BeforeAgentInstaller.java:175)
        at com.microsoft.applicationinsights.agent.internal.BeforeAgentInstaller.beforeInstallBytebuddyAgent(BeforeAgentInstal
ler.java:83)
        at io.opentelemetry.javaagent.tooling.BeforeAgentInstaller.beforeInstallBytebuddyAgent(BeforeAgentInstaller.java:9)
        ... 25 common frames omitted
Caused by: com.microsoft.applicationinsights.internal.config.connection.InvalidConnectionStringException: Could not parse conn
ection string.
        at com.microsoft.applicationinsights.internal.config.connection.ConnectionString.parseInto(ConnectionString.java:35)
        at com.microsoft.applicationinsights.TelemetryConfiguration.setConnectionString(TelemetryConfiguration.java:228)
        ... 30 common frames omitted
```

**Comment by trask** [comment]
hi @WoodenAndrew, the reason for env vars overriding the json config file, is that env vars are the easiest way to modify settings in many environments (e.g. containers), and so it's convenient to put defaults in your json config file, and then override them as needed via env vars

**Comment by WoodenAndrew** [comment]
Project specific configuration should always trump the host configuration, because it is necessary for that particular project. 

We had found this by accident since we use same VM for multiple applications. As a result, if we want to do migration deployments that switch from one application insights instance to another, under current assumption that environment variables trump particular configurations, we would need to provision a new VM, which isn't in our control. We would like you to change this behavior because it is inconsistent with the rest of software that provides configuration from multiple sources.

**Comment by trask** [comment]
> it is inconsistent with the rest of software that provides configuration from multiple sources

I'm not sure this is the case, for example Spring Boot, which is probably the most popular Java environment, follows the same behavior where env vars override file-based configuration sources
