### ISSUE TITLE
Drop dependency on apache commons

### ISSUE THREAD

**Issue by WoodenAndrew** [microsoft/ApplicationInsights-Java#1849]
Apache commons (and other "standard lib extension" libraries) are "supposed" to help in development by extending the standard library and providing helpers. Issue comes along when everyone are using different versions of "same" dependency, which in turn causes issues when trying to use other libraries. Since agents are not isolated from regular classpath in java, this causes issues when the said agent is trying to fetch classes already loaded in the JVM, which in turn might cause behavioral discrepancies when trying to run the agent and try to figure out *why* it broke.

### Expected behavior
Agent is written in plain old java without depending on any of the libraries

### Actual behavior
Agent has the following dependencies:
* com.google.guava:guava-bom:30.1.1-jre
* commons-codec:commons-codec:1.15
* commons-io:commons-io:2.7
* org.apache.commons:commons-lang3:3.7
* org.apache.commons:commons-text:1.9
* com.google.code.gson:gson:2.8.2

Probably missed some.

### To Reproduce
Delete `~/AppData/Local/Temp/transmissions` folder to show dependency on apache-commons-io while application is running with insights agent.

#### Sample Application
None.

### System information
Please provide the following information:
 - SDK Version: 3.1.1 Agent
 - OS type and version: Windows 10 build 18363
 - Application Server type and version (if applicable): None
 - Using spring-boot? Yes, but irrelevant.
 - Additional relevant libraries (with version, if applicable):
Mentioned in actual behavior.
### Logs
2021-08-12 09:06:19.556+03 ERROR c.m.a.i.c.c.TransmissionFileSystemOutput - Error fetching oldest file
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: ~\AppData\Local\Temp\transmissions
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:2629)
	at org.apache.commons.io.FileUtils.innerListFilesOrDirectories(FileUtils.java:1543)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:1876)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:1899)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.fetchOldestFromCache(TransmissionFileSystemOutput.java:343)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.fetchOldestFile(TransmissionFileSystemOutput.java:170)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.fetchNext(ActiveTransmissionLoader.java:171)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.access$300(ActiveTransmissionLoader.java:40)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader$1.run(ActiveTransmissionLoader.java:105)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-08-12 09:06:19.556+03 ERROR c.m.a.i.c.c.TransmissionFileSystemOutput - Error fetching oldest file
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: ~\AppData\Local\Temp\transmissions
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:2629)
	at org.apache.commons.io.FileUtils.innerListFilesOrDirectories(FileUtils.java:1543)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:1876)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:1899)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.fetchOldestFromCache(TransmissionFileSystemOutput.java:343)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionFileSystemOutput.fetchOldestFile(TransmissionFileSystemOutput.java:170)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.fetchNext(ActiveTransmissionLoader.java:171)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader.access$300(ActiveTransmissionLoader.java:40)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionLoader$1.run(ActiveTransmissionLoader.java:105)
	at java.base/java.lang.Thread.run(Thread.java:834)

I am not sure why the transmissions folder disappeared in the first place, but here we are.

**Comment by WoodenAndrew** [comment]
Then why/how did my commons-io:2.4 leak into agent calls?

**Comment by trask** [comment]
that's the agent's internal copy of commons-io which is only loaded inside of the agent's class loader
