### ISSUE TITLE
NullPointerException with Elasticsearch REST client (3.2.0-BETA.2)

### ISSUE THREAD

**Issue by derkoe** [microsoft/ApplicationInsights-Java#1863]
### Expected behavior
Using the agent with the Elasticsearch client should work.

### Actual behavior
`java.lang.NullPointerException: null` is thrown when using the Elasticsearch REST client.
The NPE is raised here:
```
io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpClientRequest.getPeerPort(ApacheHttpClientRequest.java:126)
```

### To Reproduce
Call `IndicesClient.exists` with the Elastic REST Client.

#### Sample Application
-

### System information
Please provide the following information:
 - SDK Version: 3.2.0-BETA.2
 - OS type and version: `Linux f80edee275f2 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64`
 - Application Server type and version (if applicable): Spring Boot
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable): https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-client/7.11.2/jar

### Logs
```
2021-08-23T09:12:24.916896360Z Caused by: java.lang.RuntimeException: null
2021-08-23T09:12:24.916900560Z 	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:887) ~[elasticsearch-rest-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916904960Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283) ~[elasticsearch-rest-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916909260Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916913560Z 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1621) ~[elasticsearch-rest-high-level-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916917960Z 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1606) ~[elasticsearch-rest-high-level-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916921960Z 	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963) ~[elasticsearch-rest-high-level-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.916926760Z 	at myapp.elasticsearch.repository.impl.ElasticsearchBaseMethodsRepositoryImpl.indexExists(ElasticsearchBaseMethodsRepositoryImpl.java:473) ~[myapp.jar!/:5.0.0-SNAPSHOT]
2021-08-23T09:12:24.916932160Z 	at myapp.data.importer.ElasticsearchDataImporter.lambda$importSettings$2(ElasticsearchDataImporter.java:197) ~[myapp.jar!/:5.0.0-SNAPSHOT]
2021-08-23T09:12:24.916936960Z 	at java.base/java.util.LinkedHashMap.forEach(Unknown Source) ~[na:na]
2021-08-23T09:12:24.916941361Z 	at myapp.data.importer.ElasticsearchDataImporter.importSettings(ElasticsearchDataImporter.java:196) ~[myapp.jar!/:5.0.0-SNAPSHOT]
2021-08-23T09:12:24.916948961Z 	at myapp.elasticsearch.repository.impl.ElasticsearchDealerRepositoryImpl.afterPropertiesSet(ElasticsearchDealerRepositoryImpl.java:285) ~[myapp.jar!/:5.0.0-SNAPSHOT]
2021-08-23T09:12:24.916953561Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.6.jar!/:5.3.6]
2021-08-23T09:12:24.916957961Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.6.jar!/:5.3.6]
2021-08-23T09:12:24.916962461Z 	... 102 common frames omitted
2021-08-23T09:12:24.916966561Z Caused by: java.lang.NullPointerException: null
2021-08-23T09:12:24.916970561Z 	at io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpClientRequest.getPeerPort(ApacheHttpClientRequest.java:126) ~[na:na]
2021-08-23T09:12:24.916974661Z 	at io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpAsyncClientNetAttributesExtractor.peerPort(ApacheHttpAsyncClientNetAttributesExtractor.java:29) ~[na:na]
2021-08-23T09:12:24.916978861Z 	at io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpAsyncClientNetAttributesExtractor.peerPort(ApacheHttpAsyncClientNetAttributesExtractor.java:13) ~[na:na]
2021-08-23T09:12:24.916982761Z 	at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.net.NetAttributesExtractor.onStart(NetAttributesExtractor.java:27) ~[na:na]
2021-08-23T09:12:24.916986361Z 	at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:146) ~[na:na]
2021-08-23T09:12:24.916990362Z 	at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.ClientInstrumenter.start(ClientInstrumenter.java:26) ~[na:na]
2021-08-23T09:12:24.916995262Z 	at io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpAsyncClientInstrumentation$DelegatingRequestProducer.generateRequest(ApacheHttpAsyncClientInstrumentation.java:108) ~[na:na]
2021-08-23T09:12:24.917000462Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
2021-08-23T09:12:24.917004862Z 	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
2021-08-23T09:12:24.917009462Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:279) ~[elasticsearch-rest-client-7.11.2.jar!/:7.11.2]
2021-08-23T09:12:24.917013762Z 	... 113 common frames omitted
```

**Comment by derkoe** [comment]
Just found this https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3659 which seems the cause.

**Comment by trask** [comment]
hey @derkoe, good find! that fix should be in the latest SNAPSHOT build: https://github.com/microsoft/ApplicationInsights-Java/files/7035690/applicationinsights-agent-3.2.0-BETA.3-SNAPSHOT.jar.zip

**Comment by derkoe** [comment]
The current SNAPSHOT works.
