### ISSUE TITLE
Application Insights could not send telemetry 

### ISSUE THREAD

**Issue by konjp** [microsoft/ApplicationInsights-Java#1871]
When application jar is deployed on Azure App Service, application is not stared. From log entries this have to do with application insights agent. When agent is disabled application starts normally. Strange thing is that log messages are complaining about cannot resolve host address, that might suggest something with DNS. But in our setup we do not have virtual network or vpn of any kind. Azure have full control of server where application is running.

Edit. When we disabled application insights agent, and because application is calling external URL's, we can say that URL's resolution is working, no problem with DNS. 
 
### System information
Please provide the following information:
 - SDK Version: java 11
 - OS type and version: Linux on Azure App Service
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable) : applicationinsights-agent 3.1.1

Exceptions in logs:

`c.m.a.i.c.c.TransmissionNetworkOutput - Unable to send telemetry to the ingestion service (telemetry will be stored to disk): wrong host address or cannot reach address due to network issues: java.net.UnknownHostException: westeurope-5.in.applicationinsights.azure.com: Try again
java.net.UnknownHostException: westeurope-5.in.applicationinsights.azure.com: Try again
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.microsoft.applicationinsights.internal.channel.common.LazyHttpClient.doExecute(LazyHttpClient.java:137)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:144)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

` c.m.a.i.c.c.TransmissionNetworkOutput - In the last 5 minutes, the following operation has failed 21 times (out of 25):
Unable to send telemetry to the ingestion service (telemetry will be stored to disk):
  wrong host address or cannot reach address due to network issues: java.net.UnknownHostException: dc.services.visualstudio.com (5 times)
 wrong host address or cannot reach address due to network issues: java.net.UnknownHostException: westeurope-5.in.applicationinsights.azure.com: Try again (2 times)
 socket timeout exception: java.net.SocketTimeoutException: Read timed out (1 times)
  wrong host address or cannot reach address due to network issues: java.net.UnknownHostException: westeurope-5.in.applicationinsights.azure.com (10 times)
 wrong host address or cannot reach address due to network issues: java.net.UnknownHostException: dc.services.visualstudio.com: Try again (3 times)
`

`WARN  c.m.a.common.CommonUtils - Error resolving hostname
java.net.UnknownHostException: xxxxxxxxx: xxxxxxxxxxxxxxxx: Try again
	at java.base/java.net.InetAddress.getLocalHost(Unknown Source)
	at com.microsoft.applicationinsights.common.CommonUtils.getHostName(CommonUtils.java:46)
	at com.microsoft.applicationinsights.TelemetryClient.createInitializedContext(TelemetryClient.java:260)
	at com.microsoft.applicationinsights.TelemetryClient.getContext(TelemetryClient.java:102)
	at com.microsoft.applicationinsights.TelemetryClient.track(TelemetryClient.java:155)
	at com.microsoft.applicationinsights.internal.heartbeat.HeartBeatProvider.send(HeartBeatProvider.java:187)
	at com.microsoft.applicationinsights.internal.heartbeat.HeartBeatProvider.access$000(HeartBeatProvider.java:29)
	at com.microsoft.applicationinsights.internal.heartbeat.HeartBeatProvider$1.run(HeartBeatProvider.java:218)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: xxxxxxxxxxxxx: Try again
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	... 14 common frames omitted`

**Comment by heyams** [comment]
Looks like it's complaining about "westeurope-5.in.applicationinsights.azure.com".  Can you share your connection string and double check the stamp specific endpoint in your connection string?

**Comment by konjp** [comment]
It is configured as environment variable in App Service:
`APPLICATIONINSIGHTS_CONNECTION_STRING` : `InstrumentationKey=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/ ` 

We are using DevOps pipelines and ARM templates to deploy resources, and this connections strings is taken directly from application insights resource, no copy-paste operation. Therefore, where small chance to have wrong connection string in App Service configuration.

**Comment by heyams** [comment]
does it work when you switch to a diff connection string? please do **copy and paste** it from the application insights resource. we do find customers who used the wrong stamp specific endpoint in their connection string.

**Comment by konjp** [comment]
This is copy-paste directly from application insights resource in JSON format:
` "ConnectionString": "InstrumentationKey=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/"`

We do not have different  connection string, because we are using one application insights. This was working fine, it started to fail randomly in last couple of days.

**Comment by heyams** [comment]
in that case, i will try to repro using westeurop-5. can you share your json config?

**Comment by heyams** [comment]
I did a quick test using 3.1.1 and send telemetry to a west europe endpoint.  it works fine on my end both classic and workspace-based connection strings. please use this [instruction](https://dev.to/tsuyoshiushio/using-fiddler-for-application-insights-codeless-java-agent-with-docker-on-wsl2-3kjl) to setup fiddler to see details of your requests/response. hope that helps.

**Comment by konjp** [comment]
Is it possible that is issue is connected to [Netty Document How To Switch DNS Resolver](https://github.com/reactor/reactor-netty/issues/1431) ?

We updated application insights agent to version 3.2.0-BETA.3 and we got this exceptions now:

`WARN  r.n.http.client.HttpClientConnect - [id:xxxxxxx, L:/xxxxxxxxx:xxxx - R:westeurope-5.in.applicationinsights.azure.com/13.69.67.60:443] The connection observed an error
java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:54)
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:41)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`
	
`WARN  r.n.http.client.HttpClientConnect - [id:xxxxxxxx, L:/xxxxxx:xxxx - R:rt.services.visualstudio.com/23.96.28.38:443] The connection observed an error
java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:54)
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:41)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`
	
`WARN  c.m.a.a.i.q.QuickPulsePingSender - Pinging live metrics endpoint: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds. (future warnings will be aggregated and logged once every 5 minutes)
reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1703)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:116)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:106)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 5 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:54)
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:41)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted`
	
`DEBUG c.m.a.a.i.q.QuickPulsePingSender - Pinging live metrics endpoint java.net.UnknownHostException: failed to resolve 'rt.services.visualstudio.com'
reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: failed to resolve 'rt.services.visualstudio.com'
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1703)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:116)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:106)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 5 common frames omitted
Caused by: java.net.UnknownHostException: failed to resolve 'rt.services.visualstudio.com'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.0.11:53] query via UDP timed out after 5000 milliseconds (no stack trace available)`

**Comment by konjp** [comment]
Any update on this?

**Comment by heyams** [comment]
Did you try jamesward's workaround from your link? 

> val httpClient = HttpClient.create().resolver(DefaultAddressResolverGroup.INSTANCE)
val webClient = WebClient.builder().clientConnector(ReactorClientHttpConnector(httpClient)).build()

io.netty.resolver.dns.**DnsNameResolverTimeoutException** is in your log.

**Comment by trask** [comment]
@heyams the exception is coming from applicationinsights, so no way for @konjp to modify the code

**Comment by heyams** [comment]
Oops, i will test it on linux app service.. we might need to implement the workaround.

**Comment by heyams** [comment]
@konjp here is the [work item](https://msazure.visualstudio.com/One/_sprints/taskboard/TelReachSDKTeam/One/CY2021H2%20-%20Nickel/Monthly/Sep?workitem=10968485) to track this issue.

**Comment by konjp** [comment]
@heyams Have you reproduced issue?

**Comment by heyams** [comment]
@konjp I can't repo using my app.  do you have a netty sample app with spring boot?

**Comment by heyams** [comment]
@konjp can you also run curl command against Application Insights and live metrics endpoints from your server to make sure there is not a firewall/networking issue? I need your help to reproduce it. thanks.

**Comment by konjp** [comment]
@heyams I think this error is not connected to spring boot application. App insights agent is running, correct me if I'm wrong, almost independently from application. Error happens before spring application is even start to initializes itself.
I had no problem to connect to application insights ingestion point from my local development machine. 
I cannot connect to a server where application is running, because docker container that Azure App Service is trying to start, actually fails because of error in agent. Therefore, server is not started.
Like is mention is that topic that I put link to that Netty client issue, this error happens randomly. 
Sometimes I can provoke it with just start/stop application from Azure App Service portal interface.

**Comment by heyams** [comment]
@konjp i have checked agent 3.1.1 was working fine on linux app services using my app. in order to help me repro, can you please share a sample app of yours (similar setup/config)? when you hit start app service, it's actually attaching the 3.1.1 agent to your app.  if the attach fails, your app won't run successfully. can you email me your connection string and full application insights log at helen.yang@microsoft.com?
