### ISSUE TITLE
Java 17 support for Java Agent 3.1.1 (GA)

### ISSUE THREAD

**Issue by petergphillips** [microsoft/ApplicationInsights-Java#1893]
We would like to upgrade to Java 17 but it doesn't appear to be compatible with the 3.1.1 version of the agent:
```
2021-09-28 16:29:11.732+01 ERROR i.o.javaagent.tooling.HelperInjector - Error preparing helpers while processing class com.zaxxer.hikari.pool.ProxyPreparedStatement for jdbc. Failed to inject helper classes into instance org.springframework.boot.loader.LaunchedURLClassLoader@7f02251
java.lang.UnsupportedOperationException: Cannot get defined package using reflection: Unsupported class file major version 61
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getDefinedPackage(ClassInjector.java:442)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:218)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:213)
	at io.opentelemetry.javaagent.tooling.HelperInjector.lambda$transform$1(HelperInjector.java:146)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.caching.WeakLockFreeCache.computeIfAbsent(WeakLockFreeCache.java:35)
	at io.opentelemetry.javaagent.tooling.HelperInjector.transform(HelperInjector.java:135)
```
The class files are compiled against java 16, but running against java 17.

The Java Agent 3.2.0-BETA.3 looks to be compatible though and pushes successfully into application insights.

Question therefore:

Will there be a new version of the 3.1 code base that is compatible with Java 17 or should we wait for 3.2 to go GA?  What is the expected timescales for 3.2 to be ready for production usage since Java 3.2.0-BETA.2 release note states:
> Note: there have been lots of implementation detail changes in this release, and we recommend to wait until 3.2.0 GA release for any production deployment.

**Comment by heyams** [comment]
We plan to GA 3.2 in October 2021.

**Comment by trask** [comment]
3.2.0-BETA.4 was just released, and is expected to be the last BETA release before it GAs

**Comment by petergphillips** [comment]
Thanks very much, good to know.  We'll give 3.2.0-BETA.4 a whirl now then.
