### ISSUE TITLE
OpenJ9 (IBM Semeru) JDK 17 + AppInsights Agent + JAVA_TOOL_OPTIONS for remote debugging

### ISSUE THREAD

**Issue by zdegner** [microsoft/ApplicationInsights-Java#2022]
### Expected behavior
Should be possible to use OpenJ9 JDK 17 with AppInsights Agent and the following JAVA_TOOL_OPTIONS for remote debugging:

JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

Originally reported as #2016, but at the time I wasn't aware it was caused by JAVA_TOOL_OPTIONS which we turn on for debugging purposes.

### Actual behavior
When using OpenJ9 JDK 17 with AppInsights Agent, the JAVA_TOOL_OPTIONS above cause this error:

_Class java/lang/reflect/Proxy$ProxyBuilder$$Lambda$9/0x00000000f0b96110 illegally accessing "private" member of class java/lang/reflect/Proxy$ProxyBuilder_

Removing the Agent or the JAVA_TOOL_OPTIONS causes the error to go away.

### To Reproduce
See sample application below
Enter an AppInsights connection string into ./src/main/jib/applicationinsights.json

./gradlew jibDockerBuild

docker run \
  -p 8080:8080 \
  -e "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" \
  --rm --name myapp \
   gcr.io/myapp/jib-image

Now try removing "-javaagent:/applicationinsights-agent-3.2.3.jar" from the build.gradle, build and rerun and notice it works now.

#### Sample Application
https://github.com/zdegner/openj9-java17-appinsights-agent

### System information
applicationinsights-agent: 3.2.3
Java: ibm-semeru-runtimes:open-17-jdk (OpenJ9 0.29.1, OpenJDK 17)
Micronaut: 3.2.2

### Logs
Message: Class java/lang/reflect/Proxy$ProxyBuilder$$Lambda$9/0x00000000f0b96110 illegally accessing "private" member of class java/lang/reflect/Proxy$ProxyBuilder
Path Taken: new NettyBinderRegistrar(ConversionService conversionService,[HttpContentProcessorResolver httpContentProcessorResolver],BeanLocator beanLocator,BeanProvider httpServerConfiguration,BeanProvider exec
utorService)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.netty.binders.NettyBinderRegistrar]

Message: Class java/lang/reflect/Proxy$ProxyBuilder$$Lambda$9/0x00000000f0b96110 illegally accessing "private" member of class java/lang/reflect/Proxy$ProxyBuilder
Path Taken: new NettyBinderRegistrar(ConversionService conversionService,[HttpContentProcessorResolver httpContentProcessorResolver],BeanLocator beanLocator,BeanProvider httpServerConfiguration,BeanProvider exec
utorService)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
        at io.micronaut.http.server.netty.binders.$NettyBinderRegistrar$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1838)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3452)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
        at com.example.Application.main(Application.java:13)
Caused by: java.lang.IllegalAccessError: Class java/lang/reflect/Proxy$ProxyBuilder$$Lambda$9/0x00000000f0b96110 illegally accessing "private" member of class java/lang/reflect/Proxy$ProxyBuilder
        at java.base/java.lang.reflect.Proxy$ProxyBuilder$$Lambda$9/0x00000000f0b96110.apply(Unknown Source)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.getDynamicModule(Proxy.java:908)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.mapToModule(Proxy.java:846)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:651)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:656)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:429)
        at java.base/java.lang.reflect.Proxy$$Lambda$285/0x00000000f1afe8d8.apply(Unknown Source)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:427)
        at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
        at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:302)
        at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:300)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:683)
        at java.base/sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:300)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:289)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
        at java.base/java.lang.Class.getAnnotationCache(Class.java:3105)
        at java.base/java.lang.Class.getAnnotation(Class.java:2690)
        at io.micronaut.core.annotation.AnnotationMetadata.isRepeatableAnnotation(AnnotationMetadata.java:1499)
        at io.micronaut.inject.annotation.DefaultAnnotationMetadata.isRepeatableAnnotation(DefaultAnnotationMetadata.java:1305)
        at io.micronaut.core.annotation.AnnotationMetadata.hasDeclaredStereotype(AnnotationMetadata.java:1464)
        at io.micronaut.core.annotation.AnnotationMetadataDelegate.hasDeclaredStereotype(AnnotationMetadataDelegate.java:514)
        at io.micronaut.inject.BeanDefinition.isIterable(BeanDefinition.java:165)
        at io.micronaut.context.DefaultApplicationContext.transformIterables(DefaultApplicationContext.java:258)
        at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:249)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3090)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3054)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2750)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
        at io.micronaut.http.server.netty.$DefaultHttpContentProcessorResolver$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        ... 18 common frames omitted

### Screenshots
n/a

**Comment by zdegner** [comment]
One possible workaround for the time being is to remove the Application Insights connection string when remote debugging is enabled.

**Comment by trask** [comment]
hi @zdegner, thanks for the repro!

it looks like this got fixed recently in the upstream OpenTelemetry Javaagent, can you give the latest SNAPSHOT build a try?

https://github.com/microsoft/ApplicationInsights-Java/suites/4889484199/artifacts/140157197

**Comment by zdegner** [comment]
Thanks @trask, I've confirmed this is working now with the _applicationinsights-agent-3.2.5-BETA-SNAPSHOT.jar_ build provided.

**Comment by trask** [comment]
awesome, we're planning to release 3.2.5-BETA next week, and 3.2.5 GA a couple of weeks after that
