### ISSUE TITLE
HTTP/1.1 header parser received no bytes

### ISSUE THREAD

**Issue by dupinderdhiman** [microsoft/ApplicationInsights-Java#2046]
### Expected behaviour
It should send a log to Azure insight and should not through any exception!

### Actual behaviour
It sends logs to Azure Insight but also through exceptions

### To Reproduce
Steps to reproduce the behaviour:
Use lastest lib! I am using 3.2.4 and trying to send logs to Azure!

### System information
Please provide the following information:
 - SDK Version: 3.2.4
 - OS type and version: docker containers!
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes with reactive 
 - Additional relevant libraries (with version, if applicable):

### Logs

```
java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:303)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:665)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:297)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:263)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$$Lambda$2359/0x00000000b0088190.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)

```

```
Request : https://<ID>.ods.opinsights.azure.com/api/logs?api-version=2016-04-01
```

![image](https://user-images.githubusercontent.com/57942222/149155124-fe87354a-c9eb-4d01-86d7-28861eaa051e.png)

**Comment by dupinderdhiman** [comment]
Hi @trask ,

It is not feasible to give you some repo to troubleshoot! but I looked for some answers related to the problem we are receiving.

The solutions seem very simple. Internet is saying just add a version with HTTP Client we use!

Like this code snippet! they said this will fix the issue. 

```
HttpClient.newBuilder()
.version(Version.HTTP_1_1)
.build();

```

**Comment by trask** [comment]
interesting, did your code (without version) work without the Application Insights Javaagent? if so, I'll see if I can repro, the Javaagent is not supposed to interfere with an otherwise working application. thx!

**Comment by trask** [comment]
were the underlying http calls to `https://<ID>.ods.opinsights.azure.com/api/logs?api-version=2016-04-01` working before you added `version(Version.HTTP_1_1)`? i'm trying to understand if this is just the agent alerting you to something you may have been missing (that you needed to add `version(Version.HTTP_1_1)`), or if the agent is breaking something in your application which is what is requiring you to add `version(Version.HTTP_1_1)`
