### ISSUE TITLE
'TransmissionNetworkOutput - Unable to send telemetry to the ingestion service' java agent (3.1.1)

### ISSUE THREAD

**Issue by WANdmurph** [microsoft/ApplicationInsights-Java#2054]
We are using Application Insights to support remote use cases. One of our agents on a 3rd party system is not pushing data to our workspace. Error reported appears to have same stack as https://github.com/microsoft/ApplicationInsights-Java/issues/1301 except for small changes between SDK versions.

We have tried to troubleshoot with the `DEBUG` level selfDiagnostic but haven't found any other indications of the cause, besides the trace below. Would appreciate any support we could get in diagnosing likely causes for this problem. 
```
2021-12-08 18:45:45.877Z WARN  c.m.a.i.c.c.TransmissionNetworkOutput - Unable to send telemetry to the ingestion service (telemetry will be stored to disk): socket timeout exception: java.net.SocketTimeoutException: Read timed out (future failures will be aggregated and logged once every 5 minutes)
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at com.microsoft.applicationinsights.internal.channel.common.LazyHttpClient.doExecute(LazyHttpClient.java:137)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:144)
        at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Expected behavior
Agent pushes, or eventually pushes data to the workspace when the network becomes available

### Actual behavior
Application has been running with the agent attached for ~2 weeks with no data received

### To Reproduce
We have been unable to reproduce the issue, appears it may have some environmental factor

#### Sample Application
NA

### System information
Please provide the following information:
 - SDK Version: 3.1.1
 - OS type and version: Linux 3.10.0-957.48.1.el7.x86_64
 - Application Server type and version (if applicable): NA
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
Logs contain data from a 3rd party, could scrub them and provide if required

**Comment by heyams** [comment]
Please use [3.2.4 GA](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.2.4).  This has been fixed in 3.2.3+. 
Please do let us know if there is any other issue.

**Comment by WANdmurph** [comment]
@heyams Thanks, we'll try a move to that version. is there an issue we can reference to?

**Comment by heyams** [comment]
It's the same cause as this issue: https://github.com/microsoft/ApplicationInsights-Java/issues/1948 and [PR](https://github.com/microsoft/ApplicationInsights-Java/pull/1953)
