### ISSUE TITLE
agent eating up almost 100% CPU

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2112]
### Expected behavior
Describe what you expected to happen.

### Actual behavior
Describe what actually happened that was unexpected.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.2.4
 - OS type and version: Linux
 - Application Server type and version (if applicable): tomcat9-jre11
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable):

### Logs
2022-02-09 21:33:44.516Z WARN  c.m.a.a.i.q.QuickPulsePingSender - Pinging live metrics endpoint: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: rt.services.visualstudio.com/23.100.122.113:443 (future warnings will be aggregated and logged once every 5 minutes)
reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: rt.services.visualstudio.com/23.100.122.113:443
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:116)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:107)
	at com.microsoft.applicationinsights.agent.internal.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 5 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: rt.services.visualstudio.com/23.100.122.113:443
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:312)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-09 21:33:45.525Z WARN  c.m.a.a.i.i.AppIdSupplier$GetAppIdTask - Unable to retrieve appId: exception sending request to https://northeurope-0.in.applicationinsights.azure.com/api/profiles/37b76138-a43f-48af-8332-bcd6f239a345/appId (future warnings will be aggregated and logged once every 5 minutes)
reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: northeurope-0.in.applicationinsights.azure.com/52.169.64.244:443
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.microsoft.applicationinsights.agent.internal.init.AppIdSupplier$GetAppIdTask.run(AppIdSupplier.java:126)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 8 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: northeurope-0.in.applicationinsights.azure.com/52.169.64.244:443
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:312)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-09 21:34:20.015Z WARN  c.m.a.a.i.common.TelemetryTruncation - truncated RemoteDependencyData.data attribute value to 8192 characters (this message will only be logged once per attribute name, and only for at most 10 different attribute names): my SQL query
-------above line is spamming again and again----------------
2022-02-11 07:32:14.256Z WARN  c.m.a.a.i.t.BatchSpanProcessor - Queuing span: Queue is full (future warnings will be aggregated and logged once every 5 minutes)
-----more spamming-------------
2022-02-11 07:37:14.256Z WARN  c.m.a.a.i.t.BatchSpanProcessor - In the last 5 minutes, the following operation has failed 70 times (out of 2780482): Queuing span:
 * Queue is full (70 times)
  -----more spamming-------------

### Screenshots
![image](https://user-images.githubusercontent.com/59076596/153592334-7a7282ce-53d6-4be6-b4a8-1e9b85dba492.png)

**Comment by trask** [comment]
hi @Sachin1O1! can you see if this is resolved in 3.2.5? see #2074, a memory leak could definitely lead to 100% cpu due to "gc thrashing"

**Comment by Sachin1O1** [comment]
cool, I will update to 3.2.5

**Comment by trask** [comment]
@Sachin1O1 can you try with this SNAPSHOT build?

https://github.com/microsoft/ApplicationInsights-Java/suites/5324794501/artifacts/165918207

I'm not able to reproduce the issue, but I'm hopeful that this may help. thx!

**Comment by trask** [comment]
hey @Sachin1O1, looking forward to any feedback on this issue when you have time, thx!

**Comment by Sachin1O1** [comment]
Hey @trask,
Sorry, I was not able to update you soon. As we are facing this issue on prod env and we are unable to repro at dev env so I am not able to use the snapshot provided by you until it is released. For the time we are increasing the memory of the container and observing.

**Comment by trask** [comment]
hi @Sachin1O1, I updated the SNAPSHOT so that it is now exactly the same as 3.2.7 release + the one change trying to resolve your issue:

https://github.com/microsoft/ApplicationInsights-Java/suites/5515964310/artifacts/176873751

Hoping this helps with confidence to apply in production where you are seeing the issue.

**Comment by Sachin1O1** [comment]
@trask can I know what the change is?

**Comment by trask** [comment]
#2121

**Comment by trask** [comment]
hi @Sachin1O1,

3.2.8 contains a configurable option (#2165) that I'm hoping may help with this.

Can you try 3.2.8 with environment variable:

`APPLICATIONINSIGHTS_PREVIEW_BSP_DELAY_MILLIS=100`

and also try with:

`APPLICATIONINSIGHTS_PREVIEW_BSP_DELAY_MILLIS=500`

and let us know if either or both of these help?

**Comment by Sachin1O1** [comment]
Hi @trask 
What's the default value if we don't provide APPLICATIONINSIGHTS_PREVIEW_BSP_DELAY_MILLIS in the environment variable.

**Comment by Sachin1O1** [comment]
Hi @trask,
I was looking in the code and its feel like a bug. It doesn't matter if I set APPLICATIONINSIGHTS_PREVIEW_BSP_DELAY_MILLIS  to any value, It always going to set it for 100 miles.

https://github.com/microsoft/ApplicationInsights-Java/blob/main/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/OpenTelemetryConfigurer.java#:~:text=String%20delayMillisStr%20%3D%20System,ofMillis(100)).build()%3B

`
    // using BatchSpanProcessor in order to get off of the application thread as soon as possible
    BatchSpanProcessorBuilder builder = BatchSpanProcessor.builder(currExporter);

    String delayMillisStr = System.getenv("APPLICATIONINSIGHTS_PREVIEW_BSP_SCHEDULE_DELAY");
    if (delayMillisStr != null) {
      // experimenting with flushing at small interval instead of using batch size 1
      // (suspect this may be better performance on small containers)
      builder.setScheduleDelay(Duration.ofMillis(Integer.parseInt(delayMillisStr)));
    } else {
      // using batch size 1 because need to convert to SpanData as soon as possible to grab data for
      // live metrics. the real batching is done at a lower level
      builder.setMaxExportBatchSize(1);
    }

    return builder.setScheduleDelay(Duration.ofMillis(100)).build(); `

Please look into this and correct me if I am wrong :)

**Comment by trask** [comment]
@Sachin1O1 3.2.9 is released now as well, would love to hear if `APPLICATIONINSIGHTS_PREVIEW_BSP_DELAY_MILLIS` is helping

**Comment by trask** [comment]
@Sachin1O1 were you able to test this? how did it go? thx!

**Comment by Sachin1O1** [comment]
@trask yes, we tested this with delayMillis = 100, but still, have the same problem with customers running on 1 core. I think minimum resource requirements can help to understand the resource allocations. Attaching profiling snap for better understanding.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/59076596/162684891-5c5caced-12b0-4654-8607-6a9df5e87996.png)

**Comment by trask** [comment]
> I think minimum resource requirements can help to understand the resource allocations.

I don't think this will help here, because what you are seeing is unexpected.

Can you help me understand how I can reproduce this? E.g. all the details of your compute environment setup and what steps to reproduce?

This looks potentially interesting https://github.com/netty/netty/issues/10239, but I don't really understand it well enough and really need to be able to reproduce the issue myself to dig further.

**Comment by trask** [comment]
also, I'm a little suspicious of the profiling measurements since the cpu time is identical to the total time on all of these threads:

![image](https://user-images.githubusercontent.com/218610/162835938-659c12aa-4269-46a9-91e3-0094459ed7d9.png)

check out https://github.com/netty/netty/issues/5896#issuecomment-512375814

> Please also note that have something shown up as used CPU may be misleading as many profilers get confused when something is waiting in native code (as epollWait0(...)) does.

**Comment by Sachin1O1** [comment]
> > I think minimum resource requirements can help to understand the resource allocations.
> 
> I don't think this will help here, because what you are seeing is unexpected.
> 
> Can you help me understand how I can reproduce this? E.g. all the details of your compute environment setup and what steps to reproduce?
> 
> This looks potentially interesting [netty/netty#10239](https://github.com/netty/netty/issues/10239), but I don't really understand it well enough and really need to be able to reproduce the issue myself to dig further.

I also don't have any steps to reproduce it. I can just share the allotted resources info for the customer.

**Comment by Sachin1O1** [comment]
@trask any inputs ?

**Comment by trask** [comment]
@Sachin1O1 without a repro or more detailed info what those threads are doing, it's hard to make any recommendation. can you open a support ticket so we can set up a live troubleshooting session?

**Comment by trask** [comment]
hi @alexenbw! what's the support case #? were you able to capture a JFR profile? I'd love to review that, thx

also, can you update your prod to 3.2.11? I did make a change recently in https://github.com/microsoft/ApplicationInsights-Java/pull/2222 hoping that it might help with this issue

**Comment by alexenbw** [comment]
Hello @trask! The support case number is: 2203290050000836. We also have JFR profiles of the occurences. Unfortunately the colleque who has access to those is not available this week, but will be back next week. Maybe you have a way to access them via the support case as we uploaded them there.

**Comment by alexenbw** [comment]
Hello @trask! We updated the java insights agent on all our apps to version 3.2.11 and will have an eye on the CPU load. Meanwhile the colleque with access to the thread dumps and JFR profiles is back. Do you still need them?

**Comment by trask** [comment]
hi @alexenbw, sorry for the late reply, can you set `APPLICATIONINSIGHTS_PREVIEW_BSP_SCHEDULE_DELAY` environment variable to `5000`?

there is one downside to that, which is live metrics will be delayed by up to 5 seconds, but if it resolves the production cpu utilization issue, then we will know what the underlying issue is, and we will work on fixing it in a way that does not impact live metrics

**Comment by trask** [comment]
(btw I was able to get the thread dump and JFR profile from the support team, thank you!)

**Comment by alexenbw** [comment]
Hello @trask ! Since the update we did not encounter any unusual high CPO load. We would like to observe a little further using the parameters default value before changing it to 5000ms. If it is working on default, we would like to avoid any additional environment parameter. If the problem occurs again, we will set the parameter. We will keep you posted either way.

**Comment by trask** [comment]
Is anyone still experiencing this issue after updating to 3.2.11? thx!

**Comment by alexenbw** [comment]
Hello @trask ! Since the update everything seems to be fine. Btw. we did not set the `APPLICATIONINSIGHTS_PREVIEW_BSP_SCHEDULE_DELAY` parameter. The default seems to be fine for our case.

So from our point of view the problem seems to be solved. Thanks for the quick help!

**Comment by fbeltrao** [comment]
@trask , same here, using 3.2.11 seems to do the trick. Thanks!
