### ISSUE TITLE
Errors on sending metrics from AKS POD to AI

### ISSUE THREAD

**Issue by vladimirbrm** [microsoft/ApplicationInsights-Java#2160]
### Expected behavior
Send metrics from POD to AI without errors in POD log

### Actual behavior
POD log have errors related to AI

### System information
Please provide the following information:
 - SDK Version: java version "14.0.1"
 - OS type and version: Ubuntu 20.04
 - Using spring-boot - yes

My spring-boot application running in AKS and send metrics to AI
If i not set proxy configuration in Java mS JAVA_TOOL_OPTIONS metrics from POD to AI reporting successfully
**If i set a proxy:**
-Dhttp.proxyHost=PROXY_NAME -Dhttp.proxyPort=PROXY_PORT
-Dhttps.proxyHost=PROXY_NAME -Dhttp.proxyPort=PROXY_PORT
-Dhttp.nonProxyHosts=dc.applicationinsights.azure.com,dc.applicationinsights.microsoft.com,dc.services.visualstudio.com,*.in.applicationinsights.azure.com,live.applicationinsights.azure.com,rt.applicationinsights.microsoft.com,rt.services.visualstudio.com
-javaagent:/application/applicationinsights-agent.jar 

**i have errors in POD log:**
2022-03-06 07:17:32.217Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service: Error sending telemetry items: http, none, PROXY_NAME/IP:PROXY_PORT => eastus2-0.in.applicationinsights.azure.com:443, status: 403 Forbidden (future warnings will be aggregated and logged once every 5 minutes)
io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, PROXY_NAME/IP:PROXY_PORT => eastus2-0.in.applicationinsights.azure.com:443, status: 403 Forbidden
    at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200)
    at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:257)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
    at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by heyams** [comment]
@vladimirbrm can you try `https `in both host and port?

`
-Dhttps.proxyHost=PROXY_NAME  -Dhttps.proxyPort=PROXY_PORT
`

**Comment by vladimirbrm** [comment]
I changed configuration to:
-Dhttp.proxyHost=PROXY_NAME -Dhttp.proxyPort=PROXY_PORT
-Dhttps.proxyHost=PROXY_NAME -Dhttps.proxyPort=PROXY_PORT
-Dhttp.nonProxyHosts=*.applicationinsights.azure.com
-javaagent:/application/applicationinsights-agent.jar

Still have error ( but different ):

2022-03-08 06:39:30.364Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service: Error sending telemetry items: null (future warnings will be aggregated and logged once every 5 minutes)
java.nio.channels.UnresolvedAddressException: null
	at io.netty.channel.epoll.AbstractEpollChannel.checkResolvable(AbstractEpollChannel.java:337)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:744)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.handler.ssl.SslHandler.connect(SslHandler.java:712)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
	at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:457)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:942)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:229)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$8(TransportConnector.java:181)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

**Note:** I have an error in the POD log, but metrics sending to AI, so I totally confused how.
**Note1:** My mS  not pure Java but SpringBoot .

**Comment by trask** [comment]
hi @vladimirbrm, what version of Application Insights Java are you using? could it be the same issue as #2077?

**Comment by vladimirbrm** [comment]
3.2.7

**Comment by trask** [comment]
hi @vladimirbrm, I believe this may be an issue that we fixed in 3.2.11, can you try with that version?
