### ISSUE TITLE
Custom Request for threadContext in Java 17

### ISSUE THREAD

**Issue by navanneethan** [microsoft/ApplicationInsights-Java#2169]
Hi, 

When we update the application to java 17, we are facing the below issue. we are using applicationinsights-spring-boot-starter as 2.6.4 and applicationinsights-agent as 3.2.4 Need a threadcontext to handle the custom request.

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webRequestTrackingFilterRegistrationBean' defined in class path resource [com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebMvcAutoConfiguration.class]: Unsatisfied dependency expressed through method 'webRequestTrackingFilterRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webRequestTrackingFilter' defined in class path resource [com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebMvcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter]: Factory method 'webRequestTrackingFilter' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter
2022-03-10T16:43:10.2588203Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
2022-03-10T16:43:10.2589070Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
2022-03-10T16:43:10.2590127Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
2022-03-10T16:43:10.2591157Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
2022-03-10T16:43:10.2592134Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
2022-03-10T16:43:10.2593068Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2022-03-10T16:43:10.2593954Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2022-03-10T16:43:10.2594813Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2022-03-10T16:43:10.2595842Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2022-03-10T16:43:10.2596662Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
2022-03-10T16:43:10.2597581Z 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:212)
2022-03-10T16:43:10.2598596Z 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:203)
2022-03-10T16:43:10.2599622Z 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:97)
2022-03-10T16:43:10.2600593Z 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86)
2022-03-10T16:43:10.2601619Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:260)
2022-03-10T16:43:10.2602730Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:234)
2022-03-10T16:43:10.2603644Z 	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53)
2022-03-10T16:43:10.2604382Z 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5219)
2022-03-10T16:43:10.2605080Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-03-10T16:43:10.2605773Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
2022-03-10T16:43:10.2606492Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
2022-03-10T16:43:10.2607146Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-03-10T16:43:10.2607853Z 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2022-03-10T16:43:10.2608718Z 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
2022-03-10T16:43:10.2609469Z 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
2022-03-10T16:43:10.2610151Z 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
2022-03-10T16:43:10.2610900Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-03-10T16:43:10.2611536Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
2022-03-10T16:43:10.2612187Z 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
2022-03-10T16:43:10.2612806Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-03-10T16:43:10.2613479Z 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2022-03-10T16:43:10.2614346Z 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
2022-03-10T16:43:10.2615111Z 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
2022-03-10T16:43:10.2615768Z 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
2022-03-10T16:43:10.2616402Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-03-10T16:43:10.2617025Z 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
2022-03-10T16:43:10.2617668Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-03-10T16:43:10.2618304Z 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
2022-03-10T16:43:10.2618935Z 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-03-10T16:43:10.2619609Z 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
2022-03-10T16:43:10.2621475Z 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)

**Comment by trask** [comment]
hi @navanneethan! can you try just using `applicationinsights-core` 2.6.4 instead of `applicationinsights-spring-boot-starter`?

The 2.x spring boot starter doesn't really enable anything in the 3.x agent anyways, so you shouldn't lose any functionality, and this could help resolve your issue, or maybe make it clearer.

**Comment by navanneethan** [comment]
Hi @trask ,

If i use applicationinsights-core, i cant able to use ThreadContext.getRequestTelemetryContext() for custom request.

ThreadContext is not available in applicationinsights-core.

**Comment by navanneethan** [comment]
> > Hi @trask ,
> > If i use applicationinsights-core, i cant able to use ThreadContext.getRequestTelemetryContext() for custom request.
> > ThreadContext is not available in applicationinsights-core.
> 
> ah, that's available in applicationinsights-web 👍

Will it cause my original issue ??

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webRequestTrackingFilterRegistrationBean' defined in class path resource [com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsWebMvcAutoConfiguration.class]: Unsatisfied dependency expressed through method 'webRequestTrackingFilterRegistrationBean' parameter 0

**Comment by trask** [comment]
using `applicationinsights-web` will not cause that issue (that class does not exist in `applicationinsights-web`)
