### ISSUE TITLE
Trying to connect to wrong cloud?

### ISSUE THREAD

**Issue by davemedvitz** [microsoft/ApplicationInsights-Java#2226]
We are trying to use the Application Insights Agent to provide logging and telemetry data for a Java application.  We are in the Azure Government Environment.  When we configure this, we are unable to get any data into our environment, instead seeing timeouts to what appear to be URLs for Commercial Cloud Endpoints.

applicationinsights.json
```
{
        "connectionString": "InstrumentationKey=<key redacted>;EndpointSuffix=applicationinsights.us;IngestionEndpoint=https://usgovvirginia-1.in.applicationinsights.azure.us/",
        "heartbeat": {
                "intervalSeconds": 60
        },
        "selfDiagnostics": {
            "destination": "file+console",
            "level": "INFO",
             "file": {
                "path": "applicationinsights.log",
                "maxSizeMb": 5,
                "maxHistory": 5
             }
        }
}
```
applicationinsights.log
```
2022-04-12 14:22:57.361-04:00 INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.2.10 started successfully (PID 7758)
2022-04-12 14:22:57.364-04:00 INFO  c.m.applicationinsights.agent - Java version: 1.8.0_322, vendor: Red Hat, Inc., home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-1.el7_9.x86_64/jre
2022-04-12 14:23:29.658-04:00 WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service (retry): received response code: 400 (future warnings will be aggregated and logged once every 5 minutes)
2022-04-12 14:23:51.744-04:00 WARN  c.m.a.a.i.l.LocalFilePurger - 1 local telemetry file(s) in folder 'telemetry' expired after 48 hours and were deleted
2022-04-12 14:24:06.975-04:00 WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service: Error sending telemetry items: connection timed out: westus-0.in.applicationinsights.azure.com/13.86.218.248:443 (future warnings will be aggregated and logged once every 5 minutes)
io.netty.channel.ConnectTimeoutException: connection timed out: westus-0.in.applicationinsights.azure.com/13.86.218.248:443
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
2022-04-12 14:28:29.662-04:00 WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 8 times (out of 12): Sending telemetry to the ingestion service (retry):
 * Error sending telemetry items: connection timed out: westus-0.in.applicationinsights.azure.com/13.86.218.248:443 (6 times)
 * received response code: 400 (2 times)
2022-04-12 14:33:29.664-04:00 WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 8 times (out of 16): Sending telemetry to the ingestion service (retry):
 * Error sending telemetry items: connection timed out: westus-0.in.applicationinsights.azure.com/13.86.218.248:443 (8 times)
```

finally, when we change the log level to TRACE in applicationinsights.json, we can verify that at least the Instrumentation key is read and correct
```
2022-04-12 14:20:43.165-04:00 DEBUG c.m.a.a.i.telemetry.TelemetryChannel - sending telemetry to ingestion service:
{"ver":1,"name":"Statsbeat","time":"2022-04-12T18:20:38.03Z","iKey":"c4a29126-a7cb-47e5-b348-11414998b11e","tags":{"ai.internal.sdkVersion":"java:3.2.10","ai.cloud.roleInstance":"<vm name redacted>"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"name":"Attach","kind":"Measurement","value":0.0}],"properties":{"runtimeVersion":"1.8.0_322","os":"Linux","language":"java","attach":"codeless","rpId":"unknown","cikey":"<key redacted>","version":"3.2.10","rp":"unknown"}}}}
{"ver":1,"name":"Statsbeat","time":"2022-04-12T18:20:38.164Z","iKey":"c4a29126-a7cb-47e5-b348-11414998b11e","tags":{"ai.internal.sdkVersion":"java:3.2.10","ai.cloud.roleInstance":"<vm name redacted>"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"name":"Feature","kind":"Measurement","value":0.0}],"properties":{"runtimeVersion":"1.8.0_322","os":"Linux","feature":"585236496","language":"java","attach":"codeless","type":"0","cikey":"<key redacted>","version":"3.2.10","rp":"vm"}}}}
{"ver":1,"name":"Statsbeat","time":"2022-04-12T18:20:38.165Z","iKey":"c4a29126-a7cb-47e5-b348-11414998b11e","tags":{"ai.internal.sdkVersion":"java:3.2.10","ai.cloud.roleInstance":"<vm name redacted>"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"name":"Feature","kind":"Measurement","value":0.0}],"properties":{"runtimeVersion":"1.8.0_322","os":"Linux","feature":"17181966336","language":"java","attach":"codeless","type":"1","cikey":"<key redacted>","version":"3.2.10","rp":"vm"}}}}
```

As far as I can tell, there is no logging that occurs when the Instrumentation Key or Endpoints are set.

Any assistance on this would be appreciated.

**Comment by trask** [comment]
hi @davemedvitz! this should be fixed in 3.2.11
