### ISSUE TITLE
Application lockup only when running applicationinsights-agent.jar

### ISSUE THREAD

**Issue by bbishopski** [microsoft/ApplicationInsights-Java#2249]
This issue is 100% reproduceable on my MAC.  When I do not run with the agent, everything is fine.  When I run with the agent I get a lockup.  Furthermore, I tried multiple versions of the jar and found that this issue began with version 3.2.5 and continues through the latest version 3.2.11.  Version 3.2.4 works fine.

I don't know if you'll be successful reproducing, but what my application is doing is trying to make an SSL connection to another service running on my localhost, and I was doing some destructive testing and killed the second service.  Then when I run my program it tries to connect (see the stack trace) and locks up, I wind up having to kill the program.

I am not using Spring Boot, but I am using Micrometer with custom timers and counters.

Locks here and remains here indefinitely.  But only on the 3rd RETRY.  I am also using Resililence4j and if I set to 2 retries the program exits as expected, but on the 3rd retry...it locks here:

java.lang.Thread.State: RUNNABLE
    at java.net.PlainSocketImpl.socketClose0(java.base@11.0.11/Native Method)
    at java.net.AbstractPlainSocketImpl.socketPreClose(java.base@11.0.11/AbstractPlainSocketImpl.java:706)
    at java.net.AbstractPlainSocketImpl.close(java.base@11.0.11/AbstractPlainSocketImpl.java:569)
    - locked <0x000000066fc7c468> (a java.lang.Object)
    at java.net.SocksSocketImpl.close(java.base@11.0.11/SocksSocketImpl.java:1067)
    at java.net.AbstractPlainSocketImpl.doConnect(java.base@11.0.11/AbstractPlainSocketImpl.java:418)
    - locked <0x000000066fc7c408> (a java.net.SocksSocketImpl)
    at java.net.AbstractPlainSocketImpl.connectToAddress(java.base@11.0.11/AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(java.base@11.0.11/AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(java.base@11.0.11/SocksSocketImpl.java:392)
    at java.net.Socket.connect(java.base@11.0.11/Socket.java:609)
    at sun.security.ssl.SSLSocketImpl.connect(java.base@11.0.11/SSLSocketImpl.java:289)
    at sun.security.ssl.BaseSSLSocketImpl.connect(java.base@11.0.11/BaseSSLSocketImpl.java:173)
    at sun.net.NetworkClient.doConnect(java.base@11.0.11/NetworkClient.java:182)
    at sun.net.www.http.HttpClient.openServer(java.base@11.0.11/HttpClient.java:474)
    at sun.net.www.http.HttpClient.openServer(java.base@11.0.11/HttpClient.java:569)
    - locked <0x000000066fc7c320> (a sun.net.www.protocol.https.HttpsClient)
    at sun.net.www.protocol.https.HttpsClient.<init>(java.base@11.0.11/HttpsClient.java:265)
    at sun.net.www.protocol.https.HttpsClient.New(java.base@11.0.11/HttpsClient.java:372)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(java.base@11.0.11/AbstractDelegateHttpsURLConnection.java:203)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(java.base@11.0.11/HttpURLConnection.java:1187)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(java.base@11.0.11/HttpURLConnection.java:1081)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(java.base@11.0.11/AbstractDelegateHttpsURLConnection.java:189)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(java.base@11.0.11/HttpURLConnection.java:1367)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(java.base@11.0.11/HttpURLConnection.java:1342)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@11.0.11/HttpURLConnection.java:1546)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@11.0.11/HttpURLConnection.java:1520)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(java.base@11.0.11/HttpURLConnection.java:3099)
    at io.opentelemetry.javaagent.instrumentation.httpurlconnection.HttpUrlHttpAttributesExtractor.responseHeader(HttpUrlHttpAttributesExtractor.java:75)
    at io.opentelemetry.javaagent.instrumentation.httpurlconnection.HttpUrlHttpAttributesExtractor.responseHeader(HttpUrlHttpAttributesExtractor.java:17)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor.onEnd(HttpCommonAttributesExtractor.java:77)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpClientAttributesExtractor.onEnd(HttpClientAttributesExtractor.java:54)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.end(Instrumenter.java:224)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@11.0.11/HttpURLConnection.java:1520)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(java.base@11.0.11/HttpURLConnection.java:3099)
    at io.opentelemetry.javaagent.instrumentation.httpurlconnection.HttpUrlHttpAttributesExtractor.responseHeader(HttpUrlHttpAttributesExtractor.java:75)
    at io.opentelemetry.javaagent.instrumentation.httpurlconnection.HttpUrlHttpAttributesExtractor.responseHeader(HttpUrlHttpAttributesExtractor.java:17)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor.onEnd(HttpCommonAttributesExtractor.java:77)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.http.HttpClientAttributesExtractor.onEnd(HttpClientAttributesExtractor.java:54)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.instrumenter.Instrumenter.end(Instrumenter.java:224)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@11.0.11/HttpURLConnection.java:1520)
    - locked <0x0000000673ec3928> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(java.base@11.0.11/HttpURLConnection.java:3099)

**Comment by trask** [comment]
hi @bbishopski! can you try with the latest SNAPSHOT build?

   https://github.com/microsoft/ApplicationInsights-Java/suites/6289534783/artifacts/225160900

The HttpUrlConnection instrumentation has a fix that may also help your use case.

If the latest SNAPSHOT doesn't resolve the issue, can you post a small sample application that we can use to try to repro/debug with?

**Comment by bbishopski** [comment]
Thanks for the suggestion! The issue seems to be resolved in the 3.3.0-BETA-SNAPSHOT version!  We will look forward to the release of 3.3.0 !  Thanks!

**Comment by trask** [comment]
great to hear that! we are targeting release of 3.3.0-BETA at the end of this week. just guessing at this point that 3.3.0 will be released around the end of the month.
