### ISSUE TITLE
Java 18 support for Java Agent 3.3.0

### ISSUE THREAD

**Issue by petergphillips** [microsoft/ApplicationInsights-Java#2390]
We have a number of Java 18 spring boot projects (Spring Boot v2.7.1, Spring v5.3.21) that we've been running successfully with the Java Agent 3.2.11.

We've just tried upgrading to the latest java agent - 3.3.0 but have found that, although the application started up correctly, no data is written to application insights.

By setting `selfDiagnostics` to `DEBUG` there are then lots of errors in the logs similar to
```
2022-07-13 12:31:36.490+01:00 WARN  muzzleMatcher - Instrumentation skipped, mismatched references were found: servlet [class io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3InstrumentationModule] on jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7
2022-07-13 12:31:36.492+01:00 WARN  muzzleMatcher - -- <no-source> Failed to generate reference check for: ClassRef: io.opentelemetry.javaagent.instrumentation.servlet.v3_0.Servlet3Accessor$Listener extends java.lang.Object implements javax.servlet.AsyncListener on classloader jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7
java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:101)
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:855)
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:841)
	at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy$AgentTypePool.doResolve(AgentCachingPoolStrategy.java:335)
```

I've tried running the java agent 3.3.0 with Java 17 for our project and it pushes successfully to application insights, so it looks like an incompatibility with Java 18 has been introduced when moving to the java agent 3.3.0 from 3.2.11.

One odd thing is that objectweb asm has [supported](https://asm.ow2.io/versions.html) Java 18 for over a year now and that the latest version of bytebuddy (9.3) [pulls in](https://github.com/raphw/byte-buddy/blob/master/pom.xml#L64) that latest version.

I can't find anything in the release notes / documentation either to suggest that Java 18 isn't supported, just that Java 8+ is [supported](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#prerequisites).  Java 18 was released in March 2022 so I was therefore expecting it to be a supported environment.

**Comment by trask** [comment]
thx for reporting this! we'll add Java 18 to our smoke tests (#2391), it does look like there's some issue that we'll need to track down
