### ISSUE TITLE
version bump to 3.4.3 results in JVMVRFY007 with IBM JVM and WebSphere Liberty

### ISSUE THREAD

**Issue by corporate-gadfly** [microsoft/ApplicationInsights-Java#2682]
### Expected behavior
Application insights should work.

### Actual behavior
A warning is shown in the logs _(which is repeated every 5 minutes)_:
```
[11/10/22 9:27:48:814 EST] 0000001e SystemOut                                                    O 2022-11-10 09:27:48.812-05:00 WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.VerifyError: JVMVRFY007 final method overridden; class=reactor/netty/http/client/HttpClientConfig, method=connectionProvider()Lreactor/netty/resources/ConnectionProvider;
        at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
        at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.defineClass(AgentClassLoader.java:176)
        at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.findAgentClass(AgentClassLoader.java:169)
        at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:144)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:876)
        at reactor.netty.http.client.HttpClient.create(HttpClient.java:396)
        at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:141)
        at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.init(LazyHttpClient.java:111)
        at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.getDelegate(LazyHttpClient.java:73)
        at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.send(LazyHttpClient.java:142)
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:64)
        at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:117)
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
        at com.microsoft.applicationinsights.agent.internal.statsbeat.NetworkStatsbeatHttpPipelinePolicy.process(NetworkStatsbeatHttpPipelinePolicy.java:33)
        at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
        at com.azure.core.http.HttpPipeline.lambda$send$0(HttpPipeline.java:106)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4570)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4422)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4358)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4330)
        at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryPipeline.sendInternal(TelemetryPipeline.java:82)
        at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryPipeline.send(TelemetryPipeline.java:53)
        at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.internalSendByConnectionString(TelemetryItemExporter.java:126)
        at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.send(TelemetryItemExporter.java:83)
        at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.exportCurrentBatch(BatchItemProcessor.java:279)
        at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.run(BatchItemProcessor.java:177)
        at java.lang.Thread.run(Thread.java:825)
```
agent is applied in `jvm.option` using:
```
-javaagent:/opt/azure/applicationinsights/applicationinsights-agent.jar
```
with `/opt/azure/applicationinsights/applicationinsights.json` contents as follows:
```{
  "connectionString": "InstrumentationKey=REDACTED;IngestionEndpoint=https://canadacentral-1.in.applicationinsights.azure.com/",
  "preview": {
    "statsbeat": {
      "disabled": true
    }
  },
  "sampling": {
    "percentage": 100
  },
  "role": {
    "name": "UAT"
  }
}
```
### System information
Please provide the following information:
 - SDK Version:
 ```
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 8.0.7.16 - pxa6480sr7fp16-20220830_01(SR7 FP16))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220817_34480 (JIT enabled, AOT enabled)
OpenJ9   - 55f250a
OMR      - f0ddca6
IBM      - bf759bf)
JCL - 20220727_01 based on Oracle jdk8u341-b10
```
 - OS type and version: `CentOS Linux release 7.9.2009 (Core)`
 - Application Server type and version (if applicable): `WebSphere Application Server 22.0.0.9 (1.0.68.cl220920220815-1900) on IBM J9 VM, version 8.0.7.16 - pxa6480sr7fp16-20220830_01(SR7 FP16) (en_US)`
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

### Logs
```
2022-11-10 09:27:35.414-05:00 INFO  c.m.applicationinsights.agent - Application Insights Java Agent 3.4.3 started successfully (PID 25643, JVM running for 3.284 s)
2022-11-10 09:27:35.444-05:00 INFO  c.m.applicationinsights.agent - Java version: 1.8.0_341, vendor: IBM Corporation, home: /opt/IBM/WebSphere/Liberty/java/8.0/jre
2022-11-10 09:27:38.817-05:00 WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.VerifyError: JVMVRFY007 final method overridden; class=reactor/netty/http/client/HttpClientConfig, method=connectionProvider()Lreactor/netty/resources/ConnectionProvider;
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.defineClass(AgentClassLoader.java:176)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.findAgentClass(AgentClassLoader.java:169)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:144)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:876)
	at reactor.netty.http.client.HttpClient.create(HttpClient.java:396)
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:141)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.init(LazyHttpClient.java:111)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.getDelegate(LazyHttpClient.java:73)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.send(LazyHttpClient.java:142)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:64)
	at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:117)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
	at com.azure.core.http.policy.RedirectPolicy.attemptRedirect(RedirectPolicy.java:67)
	at com.azure.core.http.policy.RedirectPolicy.process(RedirectPolicy.java:46)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
	at com.azure.core.http.HttpPipeline.lambda$send$0(HttpPipeline.java:106)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:101)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:99)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:52)
	at java.lang.Thread.run(Thread.java:825)
2022-11-10 09:27:38.830-05:00 WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.VerifyError: JVMVRFY007 final method overridden; class=reactor/netty/http/client/HttpClientConfig, method=connectionProvider()Lreactor/netty/resources/ConnectionProvider;
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.defineClass(AgentClassLoader.java:176)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.findAgentClass(AgentClassLoader.java:169)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:144)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:876)
	at reactor.netty.http.client.HttpClient.create(HttpClient.java:396)
	at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:141)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.init(LazyHttpClient.java:111)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.getDelegate(LazyHttpClient.java:73)
	at com.microsoft.applicationinsights.agent.internal.httpclient.LazyHttpClient.send(LazyHttpClient.java:142)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:64)
	at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:117)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
	at com.azure.core.http.policy.RedirectPolicy.attemptRedirect(RedirectPolicy.java:67)
	at com.azure.core.http.policy.RedirectPolicy.process(RedirectPolicy.java:46)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:67)
	at com.azure.core.http.HttpPipeline.lambda$send$0(HttpPipeline.java:106)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:101)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:99)
	at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:52)
	at java.lang.Thread.run(Thread.java:825)
```

**Comment by trask** [comment]
hi @corporate-gadfly!

> final method overridden; class=reactor/netty/http/client/HttpClientConfig, method=connectionProvider()Lreactor/netty/resources/ConnectionProvider;

the overridden method was final in an earlier version, do you have another version of the agent on the command line also?

could you check if you get this error when running this small sample app from the command line? https://github.com/microsoft/ApplicationInsights-Java/wiki/Diagnose-connection-to-the-Application-Insights-backend-(3.x)#application-insights-test

**Comment by corporate-gadfly** [comment]
@trask : TY for the prompt response. And I **did see** the logging test show up in the traces log in the Application Insights Logs blade:
![image](https://user-images.githubusercontent.com/1200537/201193296-263ba2fa-5989-45aa-91b5-5325d1b34bd9.png)
[Find attached the log](https://github.com/microsoft/ApplicationInsights-Java/files/9984222/2682.log).

**Comment by trask** [comment]
thx, can you set Application Insights [self-diagnostic logging](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#self-diagnostics) to `debug` for your app which is failing, and restart, and attach the debug log (or send to trask.stalnaker@microsoft.com)?

**Comment by corporate-gadfly** [comment]
To clarify, the debug log will be in the same directory as the agent jar file? In other words, you probably don't want the application logs?

**Comment by corporate-gadfly** [comment]
N/m.. I just saw the documentation link. TY.

**Comment by corporate-gadfly** [comment]
Email sent. Hope an ad/spam blocker doesn't block the attachment.

**Comment by trask** [comment]
Thanks. Interestingly, the error in your app seems to point only to the "live metrics" connection (and not the primary telemetry ingestion connection).

I updated our sample app that you ran above, and added a sleep option, so that we can see if the issue you are seeing with live metrics is reproducible with the sample app.

Can you download this updated sample app: [app.zip](https://github.com/microsoft/ApplicationInsights-Java/files/9984542/app.zip)

unzip it

and run the same command you did earlier, but with `--sleep 60` to make it sleep for 60 seconds before ending, e.g.

`java -javaagent:applicationinsights-agent-{version}.jar -jar app.jar --sleep 60`

and attach the output?

Thx

**Comment by corporate-gadfly** [comment]
sorry for the delay.

2nd Logging line showed up:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1200537/201231593-a42b4781-21e6-4323-9db6-5bbcf25aaf03.png">
[2682-with-sleep-60.log](https://github.com/microsoft/ApplicationInsights-Java/files/9985407/2682-with-sleep-60.log)

**Comment by corporate-gadfly** [comment]
For good measure:
[2682-with-openjdk-sleep-60.log](https://github.com/microsoft/ApplicationInsights-Java/files/9985457/2682-with-openjdk-sleep-60.log)

**Comment by trask** [comment]
hi @corporate-gadfly, it looks like this test was run using:

> Java version: 1.8.0_352, vendor: Red Hat, Inc., home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el7_9.x86_64/jre

can you run it using the same IBM JVM as your application and upload log?

**Comment by corporate-gadfly** [comment]
I was just trying to see how the output would differ with the OpenJDK JVM.

Sorry didn't mean to confuse the issue, but the log with IBM J9 JVM can be found in https://github.com/microsoft/ApplicationInsights-Java/issues/2682#issuecomment-1311060770.

**Comment by trask** [comment]
oh got it thx 👍

**Comment by trask** [comment]
it looks like the live metrics connection is working in both of your command line tests.

I haven't had any luck reproducing this: #2685

based on the exception, it looks like there's still an old version of the Application Insights Java agent around somewhere, which is causing the class conflict with the 3.4.3 version.

can you try to create a small repro of this on a base websphere liberty docker image, i.e. something that you can share with us and we can debug?

**Comment by corporate-gadfly** [comment]
@trask: Unfortunately I would like to reopen this issue _(as I have multiple apps on Liberty which failed after restart and version bump to 3.4.3)_.

Could you also kindly help me get started on how to run docker based smoke tests as described in #2685? FYI, I'll be utilizing `podman` on macOS on my laptop.

**Comment by corporate-gadfly** [comment]
For reference, downgrading to 3.4.2 agent immediately _fixed_ all of our failing apps 👎 .

**Comment by trask** [comment]
@corporate-gadfly can you try with 3.4.4, and also with the latest SNAPSHOT build?

https://github.com/microsoft/ApplicationInsights-Java/suites/9427883069/artifacts/445560788

**Comment by corporate-gadfly** [comment]
@trask: This issue can be closed. I have not seen any further issues with 3.4.4.
