### ISSUE TITLE
Application Insights Java failed to connect to livediagnostics endpoint - Unable to resolve host in url

### ISSUE THREAD

**Issue by luyu12** [microsoft/ApplicationInsights-Java#2817]
### To Reproduce
I followed the [instruction](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#send-custom-telemetry-by-using-the-application-insights-classic-sdk) to set up the java agent local to send out custom telemetry data to appinsights but receiving the errors in appinsights log. see details in `Logs` section

### System information
Please provide the following information:
applicationinsights-agent-3.4.7.jar
applicationinsights-core.3.4.7
macos 13.1

### Logs
`2022-12-22 15:35:13.353-08:00 WARN  c.a.m.o.e.i.q.QuickPulsePingSender - Pinging live metrics endpoint: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer (https://westus2.livediagnostics.monitor.azure.com/QuickPulseService.svc) (future warnings will be aggregated and logged once every 5 minutes)
reactor.core.Exceptions$ReactiveException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
        at reactor.core.Exceptions.propagate(Exceptions.java:408)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Mono.block(Mono.java:1710)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:101)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:99)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:52)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 5 common frames omitted
Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
2022-12-22 15:35:13.353-08:00 WARN  c.a.m.o.e.i.q.QuickPulsePingSender - Pinging live metrics endpoint: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer (https://westus2.livediagnostics.monitor.azure.com/QuickPulseService.svc) (future warnings will be aggregated and logged once every 5 minutes)
reactor.core.Exceptions$ReactiveException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
        at reactor.core.Exceptions.propagate(Exceptions.java:408)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Mono.block(Mono.java:1710)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulsePingSender.ping(QuickPulsePingSender.java:101)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.ping(QuickPulseCoordinator.java:99)
        at com.azure.monitor.opentelemetry.exporter.implementation.quickpulse.QuickPulseCoordinator.run(QuickPulseCoordinator.java:52)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 5 common frames omitted
Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
2022-12-22 15:35:22.268-08:00 ERROR c.a.m.o.e.i.q.QuickPulsePingSender -
*************************
Application Insights Java failed to connect to https://westus2.livediagnostics.monitor.azure.com/QuickPulseService.svc`

### Error
`Description:
Unable to resolve host in url

Action:
Please update your network configuration so that the host in this url can be resolved: https://westus2.livediagnostics.monitor.azure.com/QuickPulseService.svc
Learn more about troubleshooting unknown host exception here: https://go.microsoft.com/fwlink/?linkid=2185830`

**Comment by trask** [comment]
hi @luyu12!

can you download the [ping-tool.zip](https://github.com/microsoft/ApplicationInsights-Java/files/10347617/ping-tool.zip), unzip it (extracting `ping-tool.jar`), and run:

```
java -jar ping-tool.jar "<connection string>"
```

and let us know what it outputs?

**Comment by tranttxuan** [comment]
Hello @luyu12 I encountered the same error. Do you have any ideas on how to solve it?

**Comment by trask** [comment]
hi @tranttxuan, can you open a new issue and post your logs and your result from https://github.com/microsoft/ApplicationInsights-Java/wiki/Diagnose-connection-to-the-Application-Insights-backend-(3.x)#ping-test?
