### ISSUE TITLE
version 1.0.6 doesn't support java 1.8

### ISSUE THREAD

**Issue by arroyc** [Microsoft/ApplicationInsights-Java#341]
looks like java 1.8 has some security rules which doesn't allow trackevent, flush etc to send data. It throws nullpointer exception

**Comment by OriYosefiMSFT** [comment]
Can you please elaborate and maybe give an example? I don't think we noticed any such issues.

**Comment by arroyc** [comment]
This is the exception I'm getting when I use jdk 1.8
`org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at com.microsoft.applicationinsights.internal.config.JaxbAppInsightsConfigurationBuilder.build(JaxbAppInsightsConfigurationBuilder.java:49)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:91)
	at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:74)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureTelemetryHelper.isTelemetry(AzureTelemetryHelper.java:36)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureTelemetryHelper.createEvent(AzureTelemetryHelper.java:50)
	at com.microsoftopentechnologies.windowsazurestorage.WAStorageClient.download(WAStorageClient.java:543)
	at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder.perform(AzureStorageBuilder.java:174)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:710)
	at hudson.model.Build$RunnerImpl.build(Build.java:178)
	at hudson.model.Build$RunnerImpl.doRun(Build.java:139)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:480)
	at hudson.model.Run.run(Run.java:1438)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:239)
`
This is where it gets the exception
`               try {
                    tc.trackEvent(eventName, properties, metrics);
                    tc.flush();
                } catch (Exception ex) {
                    //Logger.getLogger(AzureTelemetryHelper.class.getName()).log(Level.SEVERE, null, ex);
                }`
The same code runs fine in jdk 1.7

**Comment by debugthings** [comment]
@arroyc This looks like this is coming from your build or maybe a test as the threads come from [Hudson CI](https://eclipse.org/hudson/).

I looked at the error message `org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized. at org.apache.xerces.parsers.AbstractSAXParser.setFeature` and found a few articles that indicate that the version of [Xerces](http://xerces.apache.org/) is at fault here.

The actual call that's failing is the [com.microsoft.applicationinsights.TelemetryConfiguration.getActive()](https://github.com/Microsoft/ApplicationInsights-Java/blob/v1.0.6/core/src/main/java/com/microsoft/applicationinsights/TelemetryConfiguration.java#L69) Once the call leaves [com.microsoft.applicationinsights.internal.config.JaxbAppInsightsConfigurationBuilder.build()](https://github.com/Microsoft/ApplicationInsights-Java/blob/v1.0.7/core/src/main/java/com/microsoft/applicationinsights/internal/config/JaxbAppInsightsConfigurationBuilder.java#L41) it's in the hands of the XML parser and not Application Insights.

I would suspect that this happens when you try to run the version of Hudson (or Jenkins) you have on a new JRE and build your application. Check the answeres in the following SO article and alter the command line of your CI server.

https://stackoverflow.com/questions/25644023/error-unmarshalling-xml-in-java-8-secure-processing-org-xml-sax-saxnotrecognize

**Comment by beckylino** [comment]
@arroyc have you had the chance to try @debugthings suggestions?

**Comment by dhaval24** [comment]
@arroyc we haven't noticed this issue for a while with JDK 1.8. Did you had a chance to try this on latest SDK version 1.0.10 ? If the problem no longer persist we should be good to close this thread

**Comment by dhaval24** [comment]
@arroyc please update to latest SDK version 1.0.10. This problem doesn't persist anymore. Please reopen the issue if you find the same problem.

**Comment by aditya-bhuyan** [comment]
Please add xercesImpl-2.9.1.jar into [JDK Path]/jre/lib/endorsed directory. It would solve the issue for Java 1.8
