### ISSUE TITLE
TimeoutException when ingesting logs into AI

### ISSUE THREAD

**Issue by r-michal-ah** [microsoft/ApplicationInsights-Java#3503]
### Expected behavior

All logs should be ingested into Application Insight (AI).

### Actual behavior

exception - java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds - is thrown and because of that huge portion of logs is missing in AI.

### To Reproduce
-

### System information
Please provide the following information:
 - SDK Version: 3.4.19
 - OS type and version: alpine linus v3.18
 - Application Server type and version (if applicable): tomcat (v9.0.75)
 - Using spring-boot? yes (v2.7.12)
 - Additional relevant libraries (with version, if applicable):
 -- reactor kafka (1.3.17)

### Logs

```
2024-01-12 20:01:16.612+01:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - Sending telemetry to the ingestion service: Channel response timed out after 60000 milliseconds. (***/v2.1/track) (telemetry will be stored to disk and retried) (future warnings will be aggregated and logged once every 5 minutes)

java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.

	at com.azure.core.http.netty.implementation.AzureSdkHandler.responseTimedOut(AzureSdkHandler.java:200)

	at com.azure.core.http.netty.implementation.AzureSdkHandler.lambda$startResponseTracking$2(AzureSdkHandler.java:184)

	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)

	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)

	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.base/java.lang.Thread.run(Thread.java:829)

2024-01-13 00:06:16.621+01:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - In the last 5 minutes, the following operation has failed 1 times (out of 10): Sending telemetry to the ingestion service:

* Channel response timed out after 60000 milliseconds. (***/v2.1/track) (telemetry will be stored to disk and retried) (1 times)
```

### Screenshots
-

**Comment by heyams** [comment]
@r-michal-ah Can you increase the Netty HTTP Client with a longer max idle time?
https://github.com/Azure/azure-sdk-for-java/issues/37773#issuecomment-1852558119

**Comment by jeanbisutti** [comment]
@r-michal-ah Do you observe other failures after the first attempt to send?

`2024-01-13 00:06:16.621+01:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - In the last 5 minutes, the following operation has failed 1 times (out of 10): Sending telemetry to the ingestion service:`

**Comment by r-michal-ah** [comment]
> @r-michal-ah Can you increase the Netty HTTP Client with a longer max idle time? [Azure/azure-sdk-for-java#37773 (comment)](https://github.com/Azure/azure-sdk-for-java/issues/37773#issuecomment-1852558119)

let me try it

**Comment by r-michal-ah** [comment]
> @r-michal-ah Do you observe other failures after the first attempt to send?
> 
> `2024-01-13 00:06:16.621+01:00 WARN c.a.m.o.e.i.p.TelemetryPipeline - In the last 5 minutes, the following operation has failed 1 times (out of 10): Sending telemetry to the ingestion service:`

for some pods i can see log ingestion is resumed (some logs are lost but its fine), but for other i can see this exception 

```
java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.AzureSdkHandler.responseTimedOut(AzureSdkHandler.java:200)
        at com.azure.core.http.netty.implementation.AzureSdkHandler.lambda$startResponseTracking$2(AzureSdkHandler.java:18)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

as last one and then nothing is ingested (pods needs to be restarted)

**Comment by r-michal-ah** [comment]
hello @heyams do you have any suggestions?

**Comment by heyams** [comment]
> hello @heyams do you have any suggestions?

I will reach out to Azure SDK to see if there is an env var they support for this case.

**Comment by heyams** [comment]
@r-michal-ah you can change the idle time use this env var called `DEFAULT_CONNECTION_IDLE_TIMEOUT` ([source](https://github.com/Azure/azure-sdk-for-java/blob/2dc0a56127da7d009a31f9c1d224c34dcd2f2a5a/sdk/core/azure-core/src/main/java/com/azure/core/util/HttpClientOptions.java#L40))

However, timeouts are expected and will get retried. It's better to use a shorter timeout and let it retry sooner. 
If you concern about the log, you can change the logging level to ERROR. Hope that helps.

**Comment by heyams** [comment]
@r-michal-ah additionally, can you share applicationinsights.log with me? It's worthy of looking at the full log instead of just that single stack trace. The exception above might not be the actual cause of the failure. Thanks.

**Comment by r-michal-ah** [comment]
> @r-michal-ah additionally, can you share applicationinsights.log with me? It's worthy of looking at the full log instead of just that single stack trace. The exception above might not be the actual cause of the failure. Thanks.

of course:

```json
{
  "role": {
    "name": "service-name"
  },
  "sampling": {
    "percentage": 100
  },
  "preview": {
    "processors": [
      {
        "type": "metric-filter",
        "exclude": {
          "matchType": "regexp",
          "metricNames": [
            ".*"
          ]
        }
      }
    ],
    "sampling": {
      "overrides": [
        {
          "telemetryType": "dependency",
          "percentage": 0
        },
        {
          "telemetryType": "request",
          "percentage": 30
        }
      ]
    }
  }
}
```

**Comment by heyams** [comment]
@r-michal-ah this is applicationinsights.json. I meant the applicationinsights.log.
