### ISSUE TITLE
Connection refused: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443

### ISSUE THREAD

**Issue by kolipakakondal** [microsoft/ApplicationInsights-Java#3756]
### Expected behavior
We have a subscription for Application Insights and I'm trying to send the telemetry data through Eclipse IDE. But I'm getting a 'Connection refused' error: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443

```
2024-06-23 19:20:33.523+08:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - Sending telemetry to the ingestion service (retry from disk): Connection refused: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443 (https://eastasia-0.in.applicationinsights.azure.com/v2.1/track) (future warnings will be aggregated and logged once every 5 minutes)
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:842)
2024-06-23 19:24:59.160+08:00 WARN  c.a.m.o.e.i.q.QuickPulsePingSender - In the last 5 minutes, the following operation has failed 5 times (out of 151): Pinging live metrics endpoint:
 * io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: eastasia.livediagnostics.monitor.azure.com/[0:0:0:0:0:0:0:0]:443 (https://eastasia.livediagnostics.monitor.azure.com/QuickPulseService.svc) (5 times)
2024-06-23 19:25:04.031+08:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - In the last 5 minutes, the following operation has failed 5 times (out of 17): Sending telemetry to the ingestion service:
 * Connection refused: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443 (https://eastasia-0.in.applicationinsights.azure.com/v2.1/track) (5 times)
2024-06-23 19:25:33.531+08:00 WARN  c.a.m.o.e.i.p.TelemetryPipeline - In the last 5 minutes, the following operation has failed 8 times (out of 9): Sending telemetry to the ingestion service (retry from disk):
 * Connection refused: eastasia-0.in.applicationinsights.azure.com/[0:0:0:0:0:0:0:0]:443 (https://eastasia-0.in.applicationinsights.azure.com/v2.1/track) (8 times)
```

Please find the applicationinsights.log for more information.

I am not sure where is the problem, is it with the applicationinsights server or was it something to do with the our "connectionString" I have specified. connectionString seems to be correct which I have copied from the Application insights dashboard.

Any help on troubleshooting would be appreciated!

### Actual behavior
It should send the data to the server

### To Reproduce
- Downloaded an eclipse ide
- Downloaded applicationinsights-agent-3.4.0.jar
- Added -javaagent:/Users/xx/esp/applicationinsights-agent-3.4.0.jar
- Created a file applicationinsights.json in the same folder as agent jar and added the required content as mentioned in the doc.
- Started an eclipse
- However, I see it was unable to establish a connection to the server and not sure what went wrong.

### System information
Please provide the following information:
 - SDK Version: Java agent 3.4.0
 - OS type and version:macos arm64
 - Application Server type and version (if applicable): Java using eclipse-ide
 - Using spring-boot? NO
 - Additional relevant libraries (with version, if applicable):

### Logs

[applicationinsights.log](https://github.com/user-attachments/files/15944338/applicationinsights.log)

**Comment by trask** [comment]
hi @kolipakakondal, are you able to ping eastasia-0.in.applicationinsights.azure.com from the machine where your Java application is running?
