### ISSUE TITLE
Multi line log messages with a stack trace cannot be queried 

### ISSUE THREAD

**Issue by llama-one** [microsoft/ApplicationInsights-Java#3818]
I'm using the ApplicationInsightsAppender for logback in a spring boot app and I've noticed that when an error starts with a message followed by a multi-line stack trace, I don't see it in application insights (can't search for it) and alerts aren't generated either. Here's an example of a stack trace that isn't being sent to application insights:

`2024-08-02T10:47:28.030232076Z 2024-08-02 10:47:28.021+0000 ERROR 139 --- [ool-10-thread-1] [] c.g.g.a.j.SaleAnalyticsCalculatorTask    : error calculating 30 day status
2024-08-02T10:47:28.030275376Z
2024-08-02T10:47:28.030281776Z java.lang.NullPointerException: Cannot invoke "java.time.LocalDate.isAfter(java.time.chrono.ChronoLocalDate)" because the return value of "x.x.x.model.Sale.getTransactionDate()" is null
2024-08-02T10:47:28.030287276Z 	at x.x.x.application.SaleAnalyticsService.lambda$calculateStats$1(SaleAnalyticsService.java:51)
2024-08-02T10:47:28.030303477Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
2024-08-02T10:47:28.030307777Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2024-08-02T10:47:28.030311777Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-08-02T10:47:28.030315677Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-08-02T10:47:28.030319577Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2024-08-02T10:47:28.030323477Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-08-02T10:47:28.030327377Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2024-08-02T10:47:28.030331877Z 	at x.x.x.application.SaleAnalyticsService.calculateStats(SaleAnalyticsService.java:52)
2024-08-02T10:47:28.030335877Z 	at x.x.x.application.SaleAnalyticsService.lambda$calculate30DayStats$0(SaleAnalyticsService.java:34)
2024-08-02T10:47:28.030339877Z 	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
2024-08-02T10:47:28.030355077Z 	at x.x.x.application.SaleAnalyticsService.calculate30DayStats(SaleAnalyticsService.java:34)
2024-08-02T10:47:28.030359777Z 	at x.x.x.application.jobs.SaleAnalyticsCalculatorTask.run(SaleAnalyticsCalculatorTask.java:17)
2024-08-02T10:47:28.030363777Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-08-02T10:47:28.030367677Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2024-08-02T10:47:28.030371577Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2024-08-02T10:47:28.030375578Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-08-02T10:47:28.030380778Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-08-02T10:47:28.030384778Z 	at java.base/java.lang.Thread.run(Thread.java:833)
`

On the other hand, a multi-line error message that starts with an empty first line seems to be fine. For example, I can search for this log message:

`2024-08-02T10:47:26.900421192Z 2024-08-02 10:47:26.900+0000 DEBUG 139 --- [ool-10-thread-1] [] org.hibernate.SQL                        :
2024-08-02T10:47:26.900479093Z     select
2024-08-02T10:47:26.900486693Z         distinct s1_0.pos_id,
2024-08-02T10:47:26.900491693Z         s1_0.closed_date,
2024-08-02T10:47:26.900495593Z         s1_0.created_by,
2024-08-02T10:47:26.900499493Z         s1_0.created_date,
2024-08-02T10:47:26.900503393Z         c1_0.id,
2024-08-02T10:47:26.900507293Z         c1_0.created_by,
2024-08-02T10:47:26.900511093Z         c1_0.created_date,
2024-08-02T10:47:26.900514993Z         c1_0.first_name,
2024-08-02T10:47:26.900518793Z         c1_0.last_modified_by,
2024-08-02T10:47:26.900522693Z         c1_0.last_modified_date,
2024-08-02T10:47:26.900526494Z         c1_0.last_name,
2024-08-02T10:47:26.900530294Z         c1_0.version,
2024-08-02T10:47:26.900534094Z         s1_0.delivery_method,
2024-08-02T10:47:26.900537994Z         s1_0.foreign_wire_payment,
2024-08-02T10:47:26.900541894Z         s1_0.in_repair,
2024-08-02T10:47:26.900545694Z         s1_0.last_modified_by,
2024-08-02T10:47:26.900549494Z         s1_0.last_modified_date,
2024-08-02T10:47:26.900553494Z         s1_0.new_customer,
2024-08-02T10:47:26.900557294Z         s1_0.payment_information,
2024-08-02T10:47:26.900561294Z         s1_0.pos_status,
2024-08-02T10:47:26.900565094Z         s1_0.ready_to_close,
2024-08-02T10:47:26.900568994Z         s1_0.sales_person_one,
2024-08-02T10:47:26.900572794Z         s1_0.sales_person_two,
2024-08-02T10:47:26.900576594Z         s1_0.sales_tax_required,
2024-08-02T10:47:26.900580394Z         s1_0.salon,
2024-08-02T10:47:26.900588294Z         s1_0.state,
2024-08-02T10:47:26.900592094Z         s1_0.status,
2024-08-02T10:47:26.900595894Z         s1_0.third_party_payment,
2024-08-02T10:47:26.900599994Z         s1_0.total_cost,
2024-08-02T10:47:26.900603895Z         s1_0.total_cost_with_tax,
2024-08-02T10:47:26.900607795Z         s1_0.transaction_date,
2024-08-02T10:47:26.900611695Z         s1_0.version,
2024-08-02T10:47:26.900630795Z         s1_0.zip
2024-08-02T10:47:26.900635095Z     from
2024-08-02T10:47:26.900638995Z         sale s1_0
2024-08-02T10:47:26.900642995Z     left join
2024-08-02T10:47:26.900646895Z         customer c1_0
2024-08-02T10:47:26.900650795Z             on c1_0.id=s1_0.customer_id
2024-08-02T10:47:26.900654795Z     where
2024-08-02T10:47:26.901112601Z         s1_0.pos_id `

### Expected behavior
Multi line messages that don't start with an empty line should be sent to Application Insights

### Actual behavior
Multi line messages that don't start with an empty line aren't being sent to application insights (or are not visible in application insights).

### System information
Please provide the following information:
 - SDK Version: 3.5.4
 - OS type and version: Azure App Service (Linux). 
 - Application Server type and version (if applicable): N/A
 - Using spring-boot? Yes 
 - Additional relevant libraries (with version, if applicable):
applicationinsights-logging-logback:2.6.4
applicationinsights-runtime-attach:3.5.4

**Comment by trask** [comment]
hi @llama-one! can you post a small repro that we can use to troubleshoot this issue? thanks
