### ISSUE TITLE
Failure connecting with secret behind the proxy

### ISSUE THREAD

**Issue by karolmie1** [microsoft/ApplicationInsights-Java#3827]
### Expected behavior

Using aplication insights 3.5.4, 
Using CLIENTSECRET Authentication type: 

    "authentication": {
      "enabled": true,
      "type": "CLIENTSECRET",
      "clientId": "",
      "clientSecret": "",
      "tenantId": ""
    }
    
 Having my proxy defined: 
   "proxy": {
    "host": "****",
    "port": ****
  },
  
I am able to authenticate to azure application insights behind a proxy

### Actual behavior
I cannot login to Application insights through proxy: 

2024-08-06 11:25:51.749+02:00 ERROR c.a.c.i.AccessTokenCache - {"az.sdk.message":"Failed to acquire a new access token.","exception":"java.io.UncheckedIOException: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: login.microsoftonline.com/40.126.53.21:443"}

Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 10000 ms: login.microsoftonline.com/40.126.53.21:443
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

I must set proxy on the java level to circumvent this problem, but that is not desirable setting: 
-Dhttp.proxyHost=****-Dhttp.proxyPort=**** -Dhttp.nonProxyHosts='localhost|127.0.0.1|10.*.*.*'

### To Reproduce

To reproduce you would have to simply try password based authentication behind proxy

### System information
Please provide the following information:
 - SDK Version: 3.5.4
 - OS type and version: Windows
 - Application Server type and version (if applicable):  3.27.2
 - Using spring-boot? Y
 - Additional relevant libraries (with version, if applicable): N/A

**Comment by heyams** [comment]
it should work for proxy. here is the [troubleshooting guide ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=java#language-specific-troubleshooting)

**Comment by karolmie1** [comment]
Yes, and I'm reporting, that behind the proxy using this configuration: 

"proxy": {
"host": "localhost",
"port": 8888
}
does not work, and I have to set it up on application level:  -Djava.net.useSystemProxies=true -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8888 for it to work. 

But this is not ideal, I would like for the proxy settings to just work, I don't want rest of my application to have proxy settings, and yet I must provide them to use application insights

**Comment by heyams** [comment]
json config and the system properties are equivalent. Our troubleshooting docs clearly said so. I have used it in the past to monitor traffic using fiddler with clientsecret enabled. did you try without clientsecret in the json config cause' that no longer works.

please share your json config and env var via appinsightsjavahelp@microsoft.com.
