### ISSUE TITLE
NoClassDefFoundError: com/sun/management/OperatingSystemMXBean - WildFly 10/Java 8

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#432]
Found on Windows running WildFly 10 with Java 1.8.0_144:

```
AI: ERROR 21-09-2017 17:28, 238: Failed to create ProcessCpuPerformanceCounter: com/sun/management/OperatingSystemMXBean
java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean
 at com.microsoft.applicationinsights.internal.perfcounter.CpuPerformanceCounterCalculator.<init>(CpuPerformanceCounterCalculator.java:42)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessCpuPerformanceCounter.<init>(ProcessCpuPerformanceCounter.java:41)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getMutualPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:71)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getWindowsPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:94)
 at com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory.getPerformanceCounters(ProcessBuiltInPerformanceCountersFactory.java:50)
 at com.microsoft.applicationinsights.internal.perfcounter.AbstractPerformanceCounterModule.initialize(AbstractPerformanceCounterModule.java:48)
 at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initializeComponents(TelemetryConfigurationFactory.java:484)
 at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:111)
 at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:74)
 at com.microsoft.applicationinsights.TelemetryClient.<init>(TelemetryClient.java:81)
 at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.<init>(CoreAgentNotificationsHandler.java:89)
 at com.microsoft.applicationinsights.internal.agent.AgentConnector.register(AgentConnector.java:78)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.registerWebApp(WebRequestTrackingFilter.java:238)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.initialize(WebRequestTrackingFilter.java:224)
 at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.init(WebRequestTrackingFilter.java:125)
 at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
 at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:84)
 at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:97)
 at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
 at io.undertow.servlet.core.ManagedFilter.getFilter(ManagedFilter.java:66)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
 at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
 at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

The exception comes from _CpuPerformanceCounterCalculator_ which is attempting to use the _com.sun.management.OperatingSystemMXBean_ versus _java.lang.management.OperatingSystemMXBean_. It appears the com.sun.management.OperatingSystemMXBean is used for _getProcessCpuTime_ which is not available in the java.lang.* implementation.

**Comment by dhaval24** [comment]
@littleaj I believe there is a PR already for this out correct? Also is this very similar to JBoss issue out there? If so please mark it as duplicate.
