### ISSUE TITLE
Unable to run Application Insights Java Agent in JDK9

### ISSUE THREAD

**Issue by Terryxxx** [microsoft/ApplicationInsights-Java#460]
I use JDK9 , tomact9.0 and applicationinsights-agent-1.0.10.jar ,  error was thrown:

Error:
AI-Agent: ERROR 03-11-2017 10:40, 1: Agent is NOT activated: failed to load to bootstrap class loader: null
java.lang.NullPointerException
	at com.microsoft.applicationinsights.agent.internal.agent.AgentImplementation.appendJarsToBootstrapClassLoader(AgentImplementation.java:116)
	at com.microsoft.applicationinsights.agent.internal.agent.AgentImplementation.premain(AgentImplementation.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)

**Comment by grlima** [comment]
Hi @Terryxxx - thanks for publishing this. Yes, we are aware of this issue and are currently working on making sure future AppInsights SDK versions work in JDK9. Stay tuned.

**Comment by rhrr** [comment]
We have the same issue on JDK8.

Agent: applicationinsights-agent-2.0.0-BETA.jar
JDK: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Spring Boot: v1.5.7.RELEASE
OS: Windows 7 Enterprise

Error log:
AI-Agent: ERROR 22-02-2018 16:15, 1: Agent is NOT activated: failed to load to bootstrap class loader: null
java.lang.NullPointerException
        at com.microsoft.applicationinsights.agent.internal.agent.AgentImplementation.appendJarsToBootstrapClassLoader(AgentImplementation.java:113)
        at com.microsoft.applicationinsights.agent.internal.agent.AgentImplementation.premain(AgentImplementation.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

**Comment by dhaval24** [comment]
@rhhr I do not think that this is very true unless there is a very specific scenario your application is running under. Would you mind explaining the exact set up of how you are using AI Java agent. And also make sure when you are using java agent 2.0.0 Beta you need to use Application Insights core SDK also of the same version. "Agent version and SDK version should match"

**Comment by rhrr** [comment]
The application [spring boot] is deployed in Azure app service. We configured App insights for it.
It has the same version of core and web JARs [2.0.0-BETA.jar]. 

However, I'm running this application locally on my machine when this error occurs.
I was able to capture web telemetry with this setup.
Does that matter? Is the agent only supported while running on Azure platform?
I haven't yet tried running agent on Azure app service instance.

Thanks

**Comment by dhaval24** [comment]
@rhhr no it doesn't really matter. The matter that you are able to capture web telemetry is indicative that you have web and core jar. The question now comes how you have setted up your agent. I think the root cause is line 113. If I dig into the code it seems to me that you are unable to configure agent properly. 

Here is something you need to follow:
1. Agent jar and AI-Agent.xml files in the same folder.
2. You need to configure Java Opts in Catalina Bat file in Tomcat to add Agent or equivalent in linux. (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent) Here are the instructions.

This should get you up and running.

Do you create Uber Spring Boot jar? By the way just to clarify  can I make sure that you are not repackaging Java Agent inside, in Uber SpringBoot jar you might be creating ? If the answer is yes then agent doesn't work that way. You cannot repackage it inside the same jar.

**Comment by rhrr** [comment]
It's working now. The issue was with AI-Agent.xml location.
My app is packaged as Spring Boot Executable WAR file with embedded tomcat 8.5.
At some point during setting up, I misplaced AI-Agent.xml in the WAR file, but kept AI agent JAR outside. 
Co-locating both of them outside WAR file worked. 

Thanks @dhaval24  !

**Comment by dhaval24** [comment]
@rhhr great to know it worked. my pleasure :- ) I was helpful!

**Comment by littleaj** [comment]
Java 9+ support added in #971 (2.5.0-BETA)
