### ISSUE TITLE
Correlation throws when iKey set with environment variable

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#548]
```
AI: INFO 05-02-2018 11:46, 24: Skip resolving request source as the following header was not found: Request-Context
AI: ERROR 05-02-2018 11:47, 26: Failed to resolve correlation. Exception information: java.lang.IllegalArgumentException: instrumentationKey must be not null or empty
AI: TRACE 05-02-2018 11:47, 26: Stack trace generated is java.lang.IllegalArgumentException: instrumentationKey must be not null or empty
	at com.microsoft.applicationinsights.web.internal.correlation.InstrumentationKeyResolver.resolveInstrumentationKey(InstrumentationKeyResolver.java:56)
	at com.microsoft.applicationinsights.web.internal.correlation.TelemetryCorrelationUtils.retrieveApplicationCorrelationId(TelemetryCorrelationUtils.java:150)
	at com.microsoft.applicationinsights.web.internal.correlation.TelemetryCorrelationUtils.addTargetAppIdForResponseHeader(TelemetryCorrelationUtils.java:281)
	at com.microsoft.applicationinsights.web.internal.correlation.TelemetryCorrelationUtils.resolveCorrelation(TelemetryCorrelationUtils.java:98)
	at com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule.onBeginRequest(WebRequestTrackingTelemetryModule.java:99)
	at com.microsoft.applicationinsights.web.internal.WebModulesContainer.invokeOnBeginRequest(WebModulesContainer.java:59)
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.invokeSafeOnBeginRequest(WebRequestTrackingFilter.java:174)
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2527)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2516)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
```
[XMLs from deployment.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/1696575/XMLs.from.deployment.zip)

**Comment by littleaj** [comment]
This could happen SDK-wide when using environment variable to set ikey

**Comment by dhaval24** [comment]
@littleaj did you find anything else on this? Will this cause issues / block stable release and needs a fix?

**Comment by dhaval24** [comment]
@littleaj were you able to get the root cause on this? I think we left this off track but may be blocker in some cases. Let me know if you need any help.
