### ISSUE TITLE
Initializing Collectd Plugin failed with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by matthieuklotz** [Microsoft/ApplicationInsights-Java#628]
Hi,

I currently try to use the Application Insights plugin for collectd on an Unix virtual machine hosted in Azure with the following system configuration :

- Ubuntu 16.04.4 LTS
- Collectd 5.5.1
- OpenJDK 1.8.0_151
- I tried with App Insights SDK 2.0.1 and 2.0.2

I have followed the [documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-collectd) but collectd does not load the plugin with the following exception :
```

Exception in thread "main" [Dynamic-linking native method java.lang.System.identityHashCode ... JNI]
java.lang.NoClassDefFoundError: com/microsoft/applicationinsights/collectd/ApplicationInsightsWriter
[Dynamic-linking native method java.lang.Throwable.getStackTraceDepth ... JNI]
[Dynamic-linking native method java.lang.Throwable.getStackTraceElement ... JNI]
Caused by: java.lang.ClassNotFoundException: com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Here's setup procedure :

```
sudo apt-get update && sudo apt-get install collectd -y
cd /usr/share/collectd/java
sudo curl https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.0.2/applicationinsights-collectd-2.0.2.jar --output applicationinsights-collectd-2.0.2.jar
sudo curl https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.0.2/applicationinsights-core-2.0.2.jar --output applicationinsights-core-2.0.2.jar

Add this section in collectd.conf :
    LoadPlugin java
    <Plugin "java">
      JVMArg "-verbose:jni"
      JVMArg "-Djava.class.path=/usr/share/collectd/java/applicationinsights-collectd-2.0.2.jar:/usr/share/collectd/java/collectd-api.jar"

      # Enabling Application Insights plugin
      LoadPlugin "com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter"

      # Configuring Application Insights plugin
      <Plugin ApplicationInsightsWriter>
        InstrumentationKey "my key"
      </Plugin>
    </Plugin>

sudo systemctl start collectd
```

Do I miss something or is there an issue in App Insights plugin?
Thanks for your time,
Best regards

**Comment by matthieuklotz** [comment]
Sorry i just found that download link in github have a redirection and my curl command does not follow the redirection. The good commands are : 

```
sudo -L curl https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.0.2/applicationinsights-collectd-2.0.2.jar --output applicationinsights-collectd-2.0.2.jar
sudo -L curl https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.0.2/applicationinsights-core-2.0.2.jar --output applicationinsights-core-2.0.2.jar
```
Sorry for this "not issue".
