### ISSUE TITLE
NoClassDefFoundError thrown from application insights 

### ISSUE THREAD

**Issue by rapatchi** [Microsoft/ApplicationInsights-Java#753]
### Expected behavior
After I call client.flush() event should be sent to AI and goal should successfully complete.

### Actual behavior
I get similar error as mentioned in #416 when I try to send a event from my maven plugin to AI.

The exception stack trace which I get is:
Exception in thread "ApacheSender43_initializer-0" java.lang.NoClassDefFoundError: com/microsoft/applicationinsights/core/dependencies/http/ConnectionReuseStrategy
        at com.microsoft.applicationinsights.core.dependencies.http.impl.client.HttpClients.custom(HttpClients.java:48)
        at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43$1.run(ApacheSender43.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.microsoft.applicationinsights.core.dependencies.http.ConnectionReuseStrategy
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 5 more

And my maven plugin goal also doesn't complete and gets stuck.

### To Reproduce
1. Clone https://github.com/rapatchi/servicefabric-mvn-cli.git repo
2. Remove thread.sleep() statement from https://github.com/rapatchi/servicefabric-mvn-cli/blob/master/sf-mesh/src/main/java/com/microsoft/servicefabric/TelemetryHelper.java file.
3. Run "mvn clean install"
4.  Run the following maven goal in any maven project folder. 
"mvn com.microsoft.servicefabric:sf-mesh:init -DapplicationName=helloworldserver"
 
### System information
Please provide the following information:
 - SDK Version: 2.0.*
 - OS type and version: Windows

**Comment by rapatchi** [comment]
To add currently I am using the work around as mentioned in #416.

**Comment by dhaval24** [comment]
@rapatchi thank you very much for creating an issue. This is the expected behavior for Application Insights. The AI SDK sends the telemetry in batches and what is happening here is that as soon as you are call the track() method the app shuts down where as the channel and hence all the associated threads die, throwing the exception.

The best is to have some sort of wait() as your doing in the finally block. @grlima @littleaj do you have any other thoughts?

**Comment by rapatchi** [comment]
@dhaval24 when we call flush() it should ideally block and send the telemetry and the return if I am not wrong right ?. Isn't this the expected behavior ?

**Comment by dhaval24** [comment]
@rapatchi I don't think so. The behavior is that, when you call flush() the SDK tries to send telemetry over wire immediately but ofcourse SDK doesn't have any control over your application. All the threads used in the SDK are daemon threads and they close as soon as program termination happens. 

Flush() doesn't block main thread in anyway.

**Comment by rapatchi** [comment]
Thanks @dhaval24. Let me know if you any other way of handling this apart form the way I did in the current code above.

**Comment by dhaval24** [comment]
@rapatchi I would encourage you to experiment with the sleep interval and reduce it as much as possible. I am closing this issue for now as this is the expected behavior of the SDK.
