### ISSUE TITLE
Custom TelemetryProcessor not working

### ISSUE THREAD

**Issue by travisnielsen** [Microsoft/ApplicationInsights-Java#862]
### Expected behavior
I'm working on a Spring Boot microservice and I'm trying to exempt Request telemetry generated by Kubernetes probe traffic at a specific URL. There doesn't seem to be an out-of-the box solution for this so I created a custom TelemetryProcessor based on [this document](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-filter-telemetry).

### Actual behavior
The custom telemetry processor never fires. It appears it is not being linked up by the Java Agent.

### To Reproduce
Application is launched via the following command:
```
java -jar user-service/target/user-service-0.0.2-SNAPSHOT.jar -javaagent:user-service/applicationinsights-agent-2.3.1.jar
```

#### Sample Application
[Full sample here](https://github.com/travisnielsen/appinsights-spring-boot-demo)
Relevant files are: [RequestFilter.java](https://github.com/travisnielsen/appinsights-spring-boot-demo/blob/master/user-service/src/main/java/io/example/RequestFilter.java) and [AI-Agent.xml](https://github.com/travisnielsen/appinsights-spring-boot-demo/blob/master/user-service/AI-Agent.xml)

### System information
Please provide the following information:
 - SDK Version: OpenJDK 1.8.0_181
 - OS type and version: Debian 9
 - Application Server type and version (if applicable): Tomcat 9.0.16
 - Using spring-boot? Yes - 2.1.3
 - Additional relevant libraries (with version, if applicable):

### Logs
Here are SDK trace logs from my laptop (macos). I'm not sure if these are important since they're mostly performance counter related.
```
TRACE 17-03-2019 21:30:06.805+0000, 1(main): Registering PC 'DeadLockDetector'
TRACE 17-03-2019 21:30:06.805+0000, 1(main): Failed to store performance counter 'DeadLockDetector', since there is already one
TRACE 17-03-2019 21:30:06.805+0000, 1(main): Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
TRACE 17-03-2019 21:30:06.805+0000, 1(main): Failed to store performance counter 'JvmHeapMemoryUsedPerformanceCounter', since there is already one
ERROR 17-03-2019 21:30:06.806+0000, 1(main): Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/8527/io': Can not read
ERROR 17-03-2019 21:30:06.806+0000, 1(main): Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read
ERROR 17-03-2019 21:30:06.806+0000, 1(main): Performance Counter JSDK_TotalMemoryPerformanceCounter: Error in file '/proc/meminfo': Can not read
TRACE 17-03-2019 21:30:06.806+0000, 1(main): Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
TRACE 17-03-2019 21:30:06.806+0000, 1(main): Failed to store performance counter 'JSDK_ProcessMemoryPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.806+0000, 1(main): Registering PC 'JSDK_ProcessCpuPerformanceCounter'
TRACE 17-03-2019 21:30:06.806+0000, 1(main): Failed to store performance counter 'JSDK_ProcessCpuPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Registering PC 'JSDK_ProcessIOPerformanceCounter'
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Failed to store performance counter 'JSDK_ProcessIOPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Registering PC 'JSDK_TotalCpuPerformanceCounter'
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Failed to store performance counter 'JSDK_TotalCpuPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Registering PC 'JSDK_TotalMemoryPerformanceCounter'
TRACE 17-03-2019 21:30:06.807+0000, 1(main): Failed to store performance counter 'JSDK_TotalMemoryPerformanceCounter', since there is already one
ERROR 17-03-2019 21:30:06.807+0000, 1(main): Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/8527/io': Can not read
ERROR 17-03-2019 21:30:06.808+0000, 1(main): Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read
ERROR 17-03-2019 21:30:06.808+0000, 1(main): Performance Counter JSDK_TotalMemoryPerformanceCounter: Error in file '/proc/meminfo': Can not read
TRACE 17-03-2019 21:30:06.808+0000, 1(main): Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
TRACE 17-03-2019 21:30:06.808+0000, 1(main): Failed to store performance counter 'JSDK_ProcessMemoryPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.808+0000, 1(main): Registering PC 'JSDK_ProcessCpuPerformanceCounter'
TRACE 17-03-2019 21:30:06.808+0000, 1(main): Failed to store performance counter 'JSDK_ProcessCpuPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Registering PC 'JSDK_ProcessIOPerformanceCounter'
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Failed to store performance counter 'JSDK_ProcessIOPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Registering PC 'JSDK_TotalCpuPerformanceCounter'
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Failed to store performance counter 'JSDK_TotalCpuPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Registering PC 'JSDK_TotalMemoryPerformanceCounter'
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Failed to store performance counter 'JSDK_TotalMemoryPerformanceCounter', since there is already one
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Registering PC 'DeadLockDetector'
TRACE 17-03-2019 21:30:06.809+0000, 1(main): Failed to store performance counter 'DeadLockDetector', since there is already one
TRACE 17-03-2019 21:30:06.810+0000, 1(main): Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
TRACE 17-03-2019 21:30:06.810+0000, 1(main): Failed to store performance counter 'JvmHeapMemoryUsedPerformanceCounter', since there is already one
INFO 17-03-2019 21:30:07.932+0000, 1(main): Specified class com.microsoft.applicationinsights.agent.internal.coresync.AgentNotificationsHandler is not present on the classpath
INFO 17-03-2019 21:30:07.932+0000, 1(main): Agent was not found. Skipping the agent registration in 0.792ms
INFO 17-03-2019 21:30:08.064+0000, 24(ActiveTransmissionNetworkOutput_1-0): Backoff has been reset.
INFO 17-03-2019 21:30:24.733+0000, 41(ActiveTransmissionNetworkOutput_2-0): Backoff has been reset.
INFO 17-03-2019 21:30:37.381+0000, 65(ActiveTransmissionNetworkOutput_1-1): Backoff has been reset.
ERROR 17-03-2019 21:31:02.405+0000, 18(PerformanceCounterContainer-0): Performance Counter JSDK_TotalMemoryPerformanceCounter: Error in file '/proc/meminfo': Error while parsing file: 'java.io.FileNotFoundException: /proc/meminfo (No such file or directory)'
ERROR 17-03-2019 21:31:02.409+0000, 18(PerformanceCounterContainer-0): Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/8527/io': Error while parsing file: 'JSDK_ProcessIOPerformanceCounter'
TRACE 17-03-2019 21:31:02.411+0000, 18(PerformanceCounterContainer-0): Stack trace generated is java.io.FileNotFoundException: /proc/8527/io (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.getCurrentIOForCurrentProcess(UnixProcessIOPerformanceCounter.java:99)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixProcessIOPerformanceCounter.report(UnixProcessIOPerformanceCounter.java:63)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

ERROR 17-03-2019 21:31:02.411+0000, 18(PerformanceCounterContainer-0): Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Error while parsing file: 'java.io.FileNotFoundException: /proc/stat (No such file or directory)'
TRACE 17-03-2019 21:31:02.412+0000, 18(PerformanceCounterContainer-0): Stack trace generated is java.io.FileNotFoundException: /proc/stat (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.getLineOfData(UnixTotalCpuPerformanceCounter.java:99)
	at com.microsoft.applicationinsights.internal.perfcounter.UnixTotalCpuPerformanceCounter.report(UnixTotalCpuPerformanceCounter.java:59)
	at com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer$1.run(PerformanceCounterContainer.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

TRACE 17-03-2019 21:31:02.412+0000, 18(PerformanceCounterContainer-0): Performance Counter: Process Private Bytes: 5.37791944E8
INFO 17-03-2019 21:31:07.603+0000, 67(ActiveTransmissionNetworkOutput_2-1): Backoff has been reset.
INFO 17-03-2019 21:31:15.216+0000, 68(ActiveTransmissionNetworkOutput_2-2): Backoff has been reset.
TRACE 17-03-2019 21:31:17.341+0000, 48(http-nio-8120-exec-1): InstrumentationKeyResolver - pending resolution of instrumentation key: 1684c4d1-ad60-46bf-9355-2f82148550e9
TRACE 17-03-2019 21:31:17.342+0000, 48(http-nio-8120-exec-1): Application correlation Id could not be retrieved (e.g. task may be pending or failed)
INFO 17-03-2019 21:31:17.524+0000, 48(http-nio-8120-exec-1): Skip resolving request source as the following header was not found: Request-Context
TRACE 17-03-2019 21:31:17.560+0000, 49(http-nio-8120-exec-2): InstrumentationKeyResolver - pending resolution of instrumentation key: 1684c4d1-ad60-46bf-9355-2f82148550e9
TRACE 17-03-2019 21:31:17.560+0000, 49(http-nio-8120-exec-2): Application correlation Id could not be retrieved (e.g. task may be pending or failed)
INFO 17-03-2019 21:31:17.589+0000, 49(http-nio-8120-exec-2): Skip resolving request source as the following header was not found: Request-Context
TRACE 17-03-2019 21:31:20.632+0000, 50(http-nio-8120-exec-3): InstrumentationKeyResolver - successfully resolved instrumentation key: 1684c4d1-ad60-46bf-9355-2f82148550e9
INFO 17-03-2019 21:31:20.638+0000, 50(http-nio-8120-exec-3): Skip resolving request source as the following header was not found: Request-Context
INFO 17-03-2019 21:31:20.729+0000, 51(http-nio-8120-exec-4): Skip resolving request source as the following header was not found: Request-Context
INFO 17-03-2019 21:31:22.624+0000, 74(ActiveTransmissionNetworkOutput_2-3): Backoff has been reset.
```
I was only able to get agent trace logs to show up once in my testing even though [I have the XML specified according to the instructions](https://github.com/travisnielsen/appinsights-spring-boot-demo/blob/8104df985a64a774532eaf961fe5dbb28b4b41f6/user-service/AI-Agent.xml#L31).
```
TRACE 17-03-2019 19:45:46.850+0000, 1(main): Outbound W3C tracing is enabled : true
TRACE 17-03-2019 19:45:46.851+0000, 1(main): Outbound W3C backport mode is enabled : true
TRACE 17-03-2019 19:45:46.853+0000, 1(main): Adding built-in instrumentation
TRACE 17-03-2019 19:45:46.853+0000, 1(main): Adding built-in JDBC Statements instrumentation
TRACE 17-03-2019 19:45:46.854+0000, 1(main): Adding built-in JDBC Prepared Statements instrumentation
TRACE 17-03-2019 19:45:46.856+0000, 1(main): Adding built-in HTTP instrumentation
TRACE 17-03-2019 19:45:46.857+0000, 1(main): Adding built-in Jedis instrumentation
TRACE 17-03-2019 19:45:46.858+0000, 1(main): Adding 'org/mule/module/client/MuleClient'
TRACE 17-03-2019 19:45:46.858+0000, 1(main): Adding 'io/example/KafkaSink'
TRACE 17-03-2019 19:45:46.858+0000, 1(main): Adding 'io/example/MainController'
INFO 17-03-2019 19:45:46.947+0000, 1(main): Successfully registered Jmx connector.
TRACE 17-03-2019 19:45:46.947+0000, 1(main): Agent is up
```

### Screenshots
Docker container after deployment:

![image](https://user-images.githubusercontent.com/3196834/54496500-0e280280-48be-11e9-8228-d1fe19581873.png)

**Comment by dhaval24** [comment]
@travisnielsen since you are using Application Insights Springboot starter, you would need to autowire the telemetry processor.  Just register the telemetry processor as a bean and it would be picked up by Autoconfiguration.

```
@Bean
public TelemetryProcessor requestFilter() {
      return new RequestFilter();
}
```
This would pick up your filter and auto configure it. 
you should be able to put this bean in : https://github.com/travisnielsen/appinsights-spring-boot-demo/blob/master/user-service/src/main/java/io/example/UserServiceApplication.java

**Comment by travisnielsen** [comment]
That works! I'll make a PR to update the documentation. Is it safe to assume values for the filter configuration should be placed in a custom setting in application.properties?

**Comment by dhaval24** [comment]
> Is it safe to assume values for the filter configuration should be placed in a custom setting in application.properties?

@travisnielsen I didn't quite get your question. Do you mean how can you specify the url's to be excluded via application.propertiers?
There is no configuration available in SDK that will pick the configuration for processor. You have to pretty much write this in the code. If you want to get that functionality you would have to write the code to pick the value from application.properties and set it in corresponding field in `RequestTelemetryFilter`.

**Comment by travisnielsen** [comment]
Yes. That's what I was asking. Your answer makes sense. Thanks for your help!
