### ISSUE TITLE
applicationinsights-web fat-jar broken on Maven with Java 11

### ISSUE THREAD

**Issue by Syquel** [microsoft/ApplicationInsights-Java#955]
### Expected behavior
If com.microsoft.azure:applicationinsights-spring-boot-starter:1.1.2 is included in the project as Maven dependency and bundled with the WAR, the application should start up.

### Actual behavior
The application throws an exception at startup.
> java.lang.SecurityException: class "com.microsoft.applicationinsights.internal.config.WebReflectionUtils"'s signer information does not match signer information of other classes in the same package

### To Reproduce
- Include com.microsoft.azure:applicationinsights-spring-boot-starter:1.1.2 as a Maven dependency in the project
- Build a WAR which bundles com.microsoft.azure:applicationinsights-spring-boot-starter:1.1.2
- Deploy on Azure WebApp Service with JRE11

### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version: Azure Windows WebApp Service
 - Application Server type and version (if applicable): Tomcat 9 (Auto-Update)
 - Application Runtime: Java 11 (Auto-Update)
 - Using spring-boot: yes
 - Additional relevant libraries (with version, if applicable):
  - com.microsoft.azure:applicationinsights-web:2.3.1
  - com.microsoft.azure:applicationinsights-core:2.3.1

### Root Cause
com.microsoft.azure:applicationinsights-web:2.3.1 is packaged and deployed to Maven Central as a fat-jar.
The fat-jar contains also the classes of com.microsoft.azure:applicationinsights-core:2.3.1, but applicationinsights-core is declared in the scope 'compile' in it's POM, which prompts the maven-war-plugin to bundle applicationinsights-core additionally to applicationinsights-web in the resulting WAR.
Because of this the classes of applicationinsights-core are duplicated on the classpath.

### Proposed Solution
Do not deploy the fat-jar of applicationinsights-web to Maven Central, but the standard Jar instead.

### Workaround
Declare applicationinsights-core as 'provided' in the dependency management section of the project POM.

**Comment by littleaj** [comment]
Java 11 support is not yet supported, but in-progress. Full support will be available in 2.5.0. We're planning to release a beta version in July.

That being said, this is good feedback and we'll fix this issue in 2.4.1

**Comment by hberrayana** [comment]
I'm still having the same issue with 2.5.0
This is the stacktrace:
```
Caused by: java.lang.SecurityException: class "com.microsoft.applicationinsights.internal.config.WebReflectionUtils"'s signer information does not match signer information of other classes in the same package
        at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1150) ~[na:na]
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:905) ~[na:na]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1014) ~[na:na]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802) ~[na:na]
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700) ~[na:na]
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623) ~[na:na]
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.<clinit>(WebRequestTrackingFilter.java:74) ~[applicationinsights-web-2.5.0.jar:na]
```

**Comment by pbvaltech** [comment]
@hberrayana I am having the same issue.  Did you manage to resolve this?

**Comment by hberrayana** [comment]
Yes, this how I included the dependency:
```
                <dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-spring-boot-starter</artifactId>
			<version>${azure.telemtry.version}</version>
			<exclusions>
				<exclusion>  <!-- declare the exclusion here -->
				<groupId>com.microsoft.azure</groupId>
				<artifactId>applicationinsights-core</artifactId>
				</exclusion>
			</exclusions> 
		</dependency>
```
