### ISSUE TITLE
class "javax.annotation.ManagedBean"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by Matthew-Kanderka** [microsoft/ApplicationInsights-Java#977]
### Expected behavior
If com.microsoft.azure:applicationinsights-agent:2.5.0-BETA is included in the project as Gradle dependency, it should start up.

### Actual behavior
`[ERROR] SpringApplication - Application run failed <org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: Constructor threw exception; nested exception is java.lang.SecurityException: class "javax.annotation.ManagedBean"'s signer information does not match signer information of other classes in the same package>org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: Constructor threw exception; nested exception is java.lang.SecurityException: class "javax.annotation.ManagedBean"'s signer information does not match signer information of other classes in the same package
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:124)
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:598)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.westjet.checkin.booking.api.Application.main(Application.groovy:60)`

### To Reproduce
Include com.microsoft.azure:applicationinsights-agent:2.5.0-BETA as a dependency

### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version:
 - Application Server type and version (if applicable): Jetty
 - Using spring-boot: Yes
 - Additional relevant libraries (with version, if applicable):
application-spring-boot-starter:2.5.0-BETA

### Screenshots
![Capture](https://user-images.githubusercontent.com/38925860/61156289-3c0a0600-a4b0-11e9-8fbf-e9adb16a0f0e.PNG)

**Comment by littleaj** [comment]
@Matthew-Kanderka , `applicationinsights-agent` is a special dependency that shouldn't be on the compile classpath. It is added to the application using the `-javaagent` JVM option. See [this section](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-agent#install-the-application-insights-agent-for-java) in the documentation for instructions configuring the agent.
